window.GRAMMAR=window.GRAMMAR||{};
window.GRAMMAR.en=[
// Verbformen im Simple Present
['Verbformen','I ___ in Bremen. (live)',['live','lives','living','lived'],'live','Bei „I“ steht im Simple Present die Grundform „live“.','Ich wohne in Bremen.','I live in Bremen.'],
['Verbformen','She ___ in London. (live)',['live','lives','living','lived'],'lives','Bei „she“ erhält das Verb im Simple Present ein -s: „lives“.','Sie wohnt in London.','She lives in London.'],
['Verbformen','They ___ English. (speak)',['speak','speaks','speaking','spoke'],'speak','Bei „they“ steht im Simple Present die Grundform „speak“.','Sie sprechen Englisch.','They speak English.'],
['Verbformen','He ___ at home. (work)',['work','works','working','worked'],'works','Bei „he“ erhält das Verb im Simple Present ein -s: „works“.','Er arbeitet zu Hause.','He works at home.'],
['Verbformen','We ___ water. (drink)',['drink','drinks','drinking','drank'],'drink','Bei „we“ steht im Simple Present die Grundform „drink“.','Wir trinken Wasser.','We drink water.'],
['Verbformen','My sister ___ books. (read)',['read','reads','reading','reader'],'reads','„My sister“ ist eine Person; im Simple Present steht „reads“.','Meine Schwester liest Bücher.','My sister reads books.'],
['Verbformen','You ___ very well. (cook)',['cook','cooks','cooking','cooked'],'cook','Bei „you“ steht im Simple Present die Grundform „cook“.','Du kochst sehr gut.','You cook very well.'],
['Verbformen','The bus ___ at eight. (leave)',['leave','leaves','leaving','left'],'leaves','„The bus“ steht in der dritten Person Einzahl: „leaves“.','Der Bus fährt um acht ab.','The bus leaves at eight.'],
['Verbformen','I ___ two children. (have)',['have','has','having','had'],'have','Bei „I“ heißt die Gegenwartsform „have“.','Ich habe zwei Kinder.','I have two children.'],
['Verbformen','She ___ a bicycle. (have)',['have','has','having','had'],'has','Bei „she“ heißt die Gegenwartsform „has“.','Sie hat ein Fahrrad.','She has a bicycle.'],
['Verbformen','We ___ ready. (be)',['am','is','are','be'],'are','Bei „we“ heißt die Gegenwartsform von „be“: „are“.','Wir sind bereit.','We are ready.'],
['Verbformen','He ___ tired. (be)',['am','is','are','be'],'is','Bei „he“ heißt die Gegenwartsform von „be“: „is“.','Er ist müde.','He is tired.'],
['Verbformen','I ___ happy. (be)',['am','is','are','be'],'am','Bei „I“ heißt die Gegenwartsform von „be“: „am“.','Ich bin glücklich.','I am happy.'],
['Verbformen','The children ___ outside. (play)',['play','plays','playing','played'],'play','„The children“ steht in der Mehrzahl: „play“.','Die Kinder spielen draußen.','The children play outside.'],
['Verbformen','My father ___ coffee. (like)',['like','likes','liking','liked'],'likes','„My father“ ist eine Person; im Simple Present steht „likes“.','Mein Vater mag Kaffee.','My father likes coffee.'],
['Verbformen','You ___ the answer. (know)',['know','knows','knowing','knew'],'know','Bei „you“ steht im Simple Present die Grundform „know“.','Du kennst die Antwort.','You know the answer.'],
['Verbformen','The shop ___ at nine. (open)',['open','opens','opening','opened'],'opens','„The shop“ steht in der dritten Person Einzahl: „opens“.','Der Laden öffnet um neun.','The shop opens at nine.'],
['Verbformen','We ___ a ticket. (need)',['need','needs','needing','needed'],'need','Bei „we“ steht im Simple Present die Grundform „need“.','Wir brauchen ein Ticket.','We need a ticket.'],
['Verbformen','My mother ___ to work. (go)',['go','goes','going','went'],'goes','Bei „my mother“ wird aus „go“ im Simple Present „goes“.','Meine Mutter geht zur Arbeit.','My mother goes to work.'],
['Verbformen','I ___ breakfast at seven. (eat)',['eat','eats','eating','ate'],'eat','Bei „I“ steht im Simple Present die Grundform „eat“.','Ich frühstücke um sieben.','I eat breakfast at seven.'],
// Zeitformen: eindeutige Zeitangaben
['Zeitformen','Yesterday I ___ to the cinema. (go)',['go','goes','went','going'],'went','„Yesterday“ weist auf die Vergangenheit hin: „went“.','Gestern ging ich ins Kino.','Yesterday I went to the cinema.'],
['Zeitformen','Last night she ___ a film. (watch)',['watch','watches','watched','watching'],'watched','„Last night“ weist auf die Vergangenheit hin: „watched“.','Letzte Nacht sah sie einen Film.','Last night she watched a film.'],
['Zeitformen','Two days ago we ___ pizza. (eat)',['eat','eats','ate','eating'],'ate','„Two days ago“ weist auf die Vergangenheit hin: „ate“.','Vor zwei Tagen aßen wir Pizza.','Two days ago we ate pizza.'],
['Zeitformen','Last week he ___ ill. (be)',['am','is','was','were'],'was','Bei „he“ heißt „be“ in der Vergangenheit „was“.','Letzte Woche war er krank.','Last week he was ill.'],
['Zeitformen','Yesterday they ___ at home. (be)',['are','is','was','were'],'were','Bei „they“ heißt „be“ in der Vergangenheit „were“.','Gestern waren sie zu Hause.','Yesterday they were at home.'],
['Zeitformen','Last Monday I ___ a new book. (buy)',['buy','buys','bought','buying'],'bought','Die Vergangenheitsform von „buy“ ist „bought“.','Letzten Montag kaufte ich ein neues Buch.','Last Monday I bought a new book.'],
['Zeitformen','Last year we ___ in Poland. (live)',['live','lives','lived','living'],'lived','„Last year“ verlangt hier die Vergangenheit: „lived“.','Letztes Jahr wohnten wir in Polen.','Last year we lived in Poland.'],
['Zeitformen','Yesterday she ___ her keys. (find)',['find','finds','found','finding'],'found','Die Vergangenheitsform von „find“ ist „found“.','Gestern fand sie ihre Schlüssel.','Yesterday she found her keys.'],
['Zeitformen','An hour ago he ___ me. (call)',['call','calls','called','calling'],'called','„An hour ago“ verlangt hier die Vergangenheit: „called“.','Vor einer Stunde rief er mich an.','An hour ago he called me.'],
['Zeitformen','Last night it ___ heavily. (rain)',['rain','rains','rained','raining'],'rained','„Last night“ verlangt hier die Vergangenheit: „rained“.','Letzte Nacht regnete es stark.','Last night it rained heavily.'],
['Zeitformen','Look! The dog is ___. (run)',['run','runs','ran','running'],'running','Nach „is“ verwendet die Verlaufsform das Verb mit -ing: „running“.','Schau! Der Hund rennt gerade.','Look! The dog is running.'],
['Zeitformen','Right now we are ___ dinner. (cook)',['cook','cooks','cooked','cooking'],'cooking','„Right now“ und „are“ zeigen eine laufende Handlung: „cooking“.','Gerade kochen wir Abendessen.','Right now we are cooking dinner.'],
['Zeitformen','At the moment she is ___. (read)',['read','reads','reading','reader'],'reading','Nach „is“ steht in der Verlaufsform „reading“.','Im Moment liest sie gerade.','At the moment she is reading.'],
['Zeitformen','Listen! The children are ___. (sing)',['sing','sings','sang','singing'],'singing','Nach „are“ steht in der Verlaufsform „singing“.','Hör zu! Die Kinder singen gerade.','Listen! The children are singing.'],
['Zeitformen','Now I am ___ for the bus. (wait)',['wait','waits','waited','waiting'],'waiting','Nach „am“ steht in der Verlaufsform „waiting“.','Jetzt warte ich gerade auf den Bus.','Now I am waiting for the bus.'],
['Zeitformen','Tomorrow I will ___ my friend. (visit)',['visit','visits','visited','visiting'],'visit','Nach „will“ steht die Grundform des Verbs: „visit“.','Morgen werde ich meinen Freund besuchen.','Tomorrow I will visit my friend.'],
['Zeitformen','Next week we will ___ to London. (travel)',['travel','travels','travelled','travelling'],'travel','Nach „will“ steht die Grundform „travel“.','Nächste Woche werden wir nach London reisen.','Next week we will travel to London.'],
['Zeitformen','Tonight she will ___ at home. (stay)',['stay','stays','stayed','staying'],'stay','Nach „will“ steht die Grundform „stay“.','Heute Abend wird sie zu Hause bleiben.','Tonight she will stay at home.'],
['Zeitformen','Soon they will ___ the answer. (know)',['know','knows','knew','knowing'],'know','Nach „will“ steht die Grundform „know“.','Bald werden sie die Antwort wissen.','Soon they will know the answer.'],
['Zeitformen','Tomorrow it will ___ warmer. (be)',['be','is','was','being'],'be','Nach „will“ steht die Grundform „be“.','Morgen wird es wärmer sein.','Tomorrow it will be warmer.'],
// Artikel und Präpositionen
['Artikel & Präpositionen','This is ___ apple. (unbestimmter Artikel)',['a','an','the','—'],'an','Vor dem Vokallaut in „apple“ steht „an“.','Das ist ein Apfel.','This is an apple.'],
['Artikel & Präpositionen','I have ___ dog. (unbestimmter Artikel)',['a','an','the','—'],'a','Vor dem Konsonantenlaut in „dog“ steht „a“.','Ich habe einen Hund.','I have a dog.'],
['Artikel & Präpositionen','She has ___ umbrella. (unbestimmter Artikel)',['a','an','the','—'],'an','Vor dem Vokallaut in „umbrella“ steht „an“.','Sie hat einen Regenschirm.','She has an umbrella.'],
['Artikel & Präpositionen','He is ___ teacher. (unbestimmter Artikel)',['a','an','the','—'],'a','Vor dem Konsonantenlaut in „teacher“ steht „a“.','Er ist Lehrer.','He is a teacher.'],
['Artikel & Präpositionen','It is ___ hour away. (unbestimmter Artikel)',['a','an','the','—'],'an','In „hour“ wird das h nicht gesprochen; daher steht „an“.','Es ist eine Stunde entfernt.','It is an hour away.'],
['Artikel & Präpositionen','She works as ___ engineer. (unbestimmter Artikel)',['a','an','the','—'],'an','Vor dem Vokallaut in „engineer“ steht „an“.','Sie arbeitet als Ingenieurin.','She works as an engineer.'],
['Artikel & Präpositionen','I live ___ Germany.',['in','on','at','to'],'in','Für Länder verwendet man hier „in“.','Ich wohne in Deutschland.','I live in Germany.'],
['Artikel & Präpositionen','The meeting is ___ Monday.',['in','on','at','by'],'on','Für Wochentage verwendet man „on“.','Das Treffen ist am Montag.','The meeting is on Monday.'],
['Artikel & Präpositionen','The train leaves ___ eight o’clock.',['in','on','at','by'],'at','Für eine genaue Uhrzeit verwendet man „at“.','Der Zug fährt um acht Uhr ab.','The train leaves at eight o’clock.'],
['Artikel & Präpositionen','I am waiting ___ the bus.',['to','for','from','with'],'for','Auf jemanden oder etwas warten heißt „wait for“.','Ich warte auf den Bus.','I am waiting for the bus.'],
['Artikel & Präpositionen','She goes ___ school.',['in','on','at','to'],'to','Eine Bewegung zur Schule wird mit „to“ ausgedrückt.','Sie geht zur Schule.','She goes to school.'],
['Artikel & Präpositionen','We travel ___ train.',['by','with','at','on'],'by','Das Verkehrsmittel drückt man hier mit „by“ aus.','Wir reisen mit dem Zug.','We travel by train.'],
['Artikel & Präpositionen','The book is ___ the table.',['in','on','at','to'],'on','Auf einer Oberfläche heißt „on“.','Das Buch liegt auf dem Tisch.','The book is on the table.'],
['Artikel & Präpositionen','My keys are ___ my bag.',['in','on','at','to'],'in','Im Inneren der Tasche heißt „in“.','Meine Schlüssel sind in meiner Tasche.','My keys are in my bag.'],
['Artikel & Präpositionen','I am ___ home.',['in','on','at','to'],'at','Die feste Wendung lautet „at home“.','Ich bin zu Hause.','I am at home.'],
['Artikel & Präpositionen','She comes ___ Poland.',['to','for','from','with'],'from','Herkunft drückt man mit „from“ aus.','Sie kommt aus Polen.','She comes from Poland.'],
['Artikel & Präpositionen','I am talking ___ my sister.',['to','for','from','on'],'to','Mit jemandem sprechen heißt „talk to“; auch „talk with“ wäre möglich.','Ich spreche mit meiner Schwester.','I am talking to my sister.'],
['Artikel & Präpositionen','This gift is ___ you.',['to','for','from','on'],'for','Ein Geschenk für jemanden: „for you“.','Dieses Geschenk ist für dich.','This gift is for you.'],
['Artikel & Präpositionen','He goes to work ___ bus.',['by','with','at','in'],'by','Das Verkehrsmittel drückt man hier mit „by“ aus.','Er fährt mit dem Bus zur Arbeit.','He goes to work by bus.'],
['Artikel & Präpositionen','We meet ___ Friday.',['in','on','at','by'],'on','Für Wochentage verwendet man „on“.','Wir treffen uns am Freitag.','We meet on Friday.']
].map(([category,prompt,options,answer,explanation,de,target])=>({category,prompt,options,answer,explanation,de,target}));
