window.GRAMMAR=window.GRAMMAR||{};
window.GRAMMAR.es=[
// Verbformen: Präsens
['Verbformen','Yo ___ en Madrid. (vivir)',['vivo','vives','vive','vivimos'],'vivo','Bei „yo“ heißt die Präsensform von „vivir“: „vivo“.','Ich wohne in Madrid.','Yo vivo en Madrid.'],
['Verbformen','Tú ___ español. (hablar)',['hablo','hablas','habla','hablamos'],'hablas','Bei „tú“ heißt die Präsensform von „hablar“: „hablas“.','Du sprichst Spanisch.','Tú hablas español.'],
['Verbformen','Ella ___ aquí. (trabajar)',['trabajo','trabajas','trabaja','trabajamos'],'trabaja','Bei „ella“ heißt die Präsensform: „trabaja“.','Sie arbeitet hier.','Ella trabaja aquí.'],
['Verbformen','Nosotros ___ pan. (comer)',['como','comes','come','comemos'],'comemos','Bei „nosotros“ heißt die Präsensform: „comemos“.','Wir essen Brot.','Nosotros comemos pan.'],
['Verbformen','Vosotros ___ agua. (beber)',['bebo','bebes','bebemos','bebéis'],'bebéis','Bei „vosotros“ heißt die Präsensform: „bebéis“.','Ihr trinkt Wasser.','Vosotros bebéis agua.'],
['Verbformen','Ellos ___ libros. (leer)',['leo','lees','lee','leen'],'leen','Bei „ellos“ heißt die Präsensform: „leen“.','Sie lesen Bücher.','Ellos leen libros.'],
['Verbformen','Yo ___ una bicicleta. (tener)',['tengo','tienes','tiene','tenemos'],'tengo','Bei „yo“ heißt „tener“ im Präsens: „tengo“.','Ich habe ein Fahrrad.','Yo tengo una bicicleta.'],
['Verbformen','Él ___ hambre. (tener)',['tengo','tienes','tiene','tenéis'],'tiene','Bei „él“ heißt „tener“ im Präsens: „tiene“.','Er hat Hunger.','Él tiene hambre.'],
['Verbformen','Nosotros ___ al cine. (ir)',['voy','vas','va','vamos'],'vamos','Bei „nosotros“ heißt „ir“ im Präsens: „vamos“.','Wir gehen ins Kino.','Nosotros vamos al cine.'],
['Verbformen','Tú ___ ayudarme. (poder)',['puedo','puedes','puede','podemos'],'puedes','Bei „tú“ heißt „poder“ im Präsens: „puedes“.','Du kannst mir helfen.','Tú puedes ayudarme.'],
['Verbformen','Ella ___ un café. (querer)',['quiero','quieres','quiere','queremos'],'quiere','Bei „ella“ heißt „querer“ im Präsens: „quiere“.','Sie möchte einen Kaffee.','Ella quiere un café.'],
['Verbformen','Yo ___ de Alemania. (ser)',['soy','eres','es','somos'],'soy','Bei „yo“ heißt „ser“ im Präsens: „soy“.','Ich komme aus Deutschland.','Yo soy de Alemania.'],
['Verbformen','Tú ___ en casa. (estar)',['estoy','estás','está','estamos'],'estás','Bei „tú“ heißt „estar“ im Präsens: „estás“.','Du bist zu Hause.','Tú estás en casa.'],
['Verbformen','El niño ___. (dormir)',['duermo','duermes','duerme','dormimos'],'duerme','Bei „el niño“ heißt die Präsensform: „duerme“.','Das Kind schläft.','El niño duerme.'],
['Verbformen','Nosotros ___ la cena. (hacer)',['hago','haces','hace','hacemos'],'hacemos','Bei „nosotros“ heißt „hacer“ im Präsens: „hacemos“.','Wir machen das Abendessen.','Nosotros hacemos la cena.'],
['Verbformen','Ella ___ la verdad. (decir)',['digo','dices','dice','decimos'],'dice','Bei „ella“ heißt „decir“ im Präsens: „dice“.','Sie sagt die Wahrheit.','Ella dice la verdad.'],
['Verbformen','Yo ___ la respuesta. (saber)',['sé','sabes','sabe','sabemos'],'sé','Bei „yo“ heißt „saber“ im Präsens: „sé“.','Ich weiß die Antwort.','Yo sé la respuesta.'],
['Verbformen','Vosotros ___ cerca. (vivir)',['vivo','vives','vivimos','vivís'],'vivís','Bei „vosotros“ heißt die Präsensform von „vivir“: „vivís“.','Ihr wohnt in der Nähe.','Vosotros vivís cerca.'],
['Verbformen','Ellos ___ temprano. (salir)',['salgo','sales','sale','salen'],'salen','Bei „ellos“ heißt „salir“ im Präsens: „salen“.','Sie gehen früh los.','Ellos salen temprano.'],
['Verbformen','Tú ___ una carta. (escribir)',['escribo','escribes','escribe','escribimos'],'escribes','Bei „tú“ heißt die Präsensform: „escribes“.','Du schreibst einen Brief.','Tú escribes una carta.'],
// Vergangenheit: Pretérito indefinido
['Vergangenheit','Ayer yo ___ al parque. (ir)',['fui','fue','fuimos','iban'],'fui','„Ayer“ heißt gestern; „ir“ lautet hier in der Vergangenheit „fui“.','Gestern ging ich in den Park.','Ayer yo fui al parque.'],
['Vergangenheit','Ayer tú ___ pan. (comprar)',['compré','compraste','compró','compramos'],'compraste','Bei „tú“ lautet die Vergangenheitsform „compraste“.','Gestern kauftest du Brot.','Ayer tú compraste pan.'],
['Vergangenheit','Anoche ella ___ agua. (beber)',['bebí','bebiste','bebió','bebimos'],'bebió','Bei „ella“ lautet die Vergangenheitsform „bebió“.','Gestern Abend trank sie Wasser.','Anoche ella bebió agua.'],
['Vergangenheit','Ayer nosotros ___ juntos. (comer)',['comí','comiste','comió','comimos'],'comimos','Bei „nosotros“ lautet die Vergangenheitsform „comimos“.','Gestern aßen wir zusammen.','Ayer nosotros comimos juntos.'],
['Vergangenheit','Ayer vosotros ___ español. (hablar)',['hablé','hablaste','habló','hablasteis'],'hablasteis','Bei „vosotros“ lautet die Vergangenheitsform „hablasteis“.','Gestern habt ihr Spanisch gesprochen.','Ayer vosotros hablasteis español.'],
['Vergangenheit','Ayer ellos ___ tiempo. (tener)',['tuve','tuviste','tuvo','tuvieron'],'tuvieron','Bei „ellos“ lautet die Vergangenheitsform von „tener“: „tuvieron“.','Gestern hatten sie Zeit.','Ayer ellos tuvieron tiempo.'],
['Vergangenheit','Anoche yo ___ la cena. (hacer)',['hice','hiciste','hizo','hicimos'],'hice','Bei „yo“ lautet die Vergangenheitsform von „hacer“: „hice“.','Gestern Abend machte ich das Abendessen.','Anoche yo hice la cena.'],
['Vergangenheit','Ayer tú ___ la verdad. (decir)',['dije','dijiste','dijo','dijimos'],'dijiste','Bei „tú“ lautet die Vergangenheitsform von „decir“: „dijiste“.','Gestern sagtest du die Wahrheit.','Ayer tú dijiste la verdad.'],
['Vergangenheit','Ayer él ___ en casa. (estar)',['estuve','estuviste','estuvo','estuvimos'],'estuvo','Bei „él“ lautet die Vergangenheitsform von „estar“: „estuvo“.','Gestern war er zu Hause.','Ayer él estuvo en casa.'],
['Vergangenheit','Anoche nosotros ___ una película. (ver)',['vi','viste','vio','vimos'],'vimos','Bei „nosotros“ lautet die Vergangenheitsform von „ver“: „vimos“.','Gestern Abend sahen wir einen Film.','Anoche nosotros vimos una película.'],
['Vergangenheit','Ayer ella ___ una carta. (escribir)',['escribí','escribiste','escribió','escribimos'],'escribió','Bei „ella“ lautet die Vergangenheitsform „escribió“.','Gestern schrieb sie einen Brief.','Ayer ella escribió una carta.'],
['Vergangenheit','Ayer yo ___ tarde. (llegar)',['llegué','llegaste','llegó','llegamos'],'llegué','Bei „yo“ schreibt man in der Vergangenheit „llegué“.','Gestern kam ich spät an.','Ayer yo llegué tarde.'],
['Vergangenheit','Ayer tú ___ temprano. (salir)',['salí','saliste','salió','salimos'],'saliste','Bei „tú“ lautet die Vergangenheitsform „saliste“.','Gestern bist du früh losgegangen.','Ayer tú saliste temprano.'],
['Vergangenheit','Ayer ellos ___ a Madrid. (ir)',['fui','fue','fuimos','fueron'],'fueron','Bei „ellos“ lautet die Vergangenheitsform von „ir“: „fueron“.','Gestern fuhren sie nach Madrid.','Ayer ellos fueron a Madrid.'],
['Vergangenheit','Ayer él ___ un problema. (tener)',['tuve','tuviste','tuvo','tuvimos'],'tuvo','Bei „él“ lautet die Vergangenheitsform von „tener“: „tuvo“.','Gestern hatte er ein Problem.','Ayer él tuvo un problema.'],
['Vergangenheit','Ayer nosotros ___ entrar. (poder)',['pude','pudiste','pudo','pudimos'],'pudimos','Bei „nosotros“ lautet die Vergangenheitsform von „poder“: „pudimos“.','Gestern konnten wir hineingehen.','Ayer nosotros pudimos entrar.'],
['Vergangenheit','Ayer ella ___ el libro aquí. (poner)',['puse','pusiste','puso','pusimos'],'puso','Bei „ella“ lautet die Vergangenheitsform von „poner“: „puso“.','Gestern legte sie das Buch hierhin.','Ayer ella puso el libro aquí.'],
['Vergangenheit','Anoche yo ___ bien. (dormir)',['dormí','dormiste','durmió','dormimos'],'dormí','Bei „yo“ lautet die Vergangenheitsform „dormí“.','Gestern Nacht schlief ich gut.','Anoche yo dormí bien.'],
['Vergangenheit','Ayer tú ___ el mensaje. (leer)',['leí','leíste','leyó','leímos'],'leíste','Bei „tú“ lautet die Vergangenheitsform „leíste“.','Gestern lasest du die Nachricht.','Ayer tú leíste el mensaje.'],
['Vergangenheit','Ayer ellos ___ a casa. (venir)',['vine','viniste','vino','vinieron'],'vinieron','Bei „ellos“ lautet die Vergangenheitsform von „venir“: „vinieron“.','Gestern kamen sie nach Hause.','Ayer ellos vinieron a casa.'],
// Artikel und Präpositionen
['Artikel & Präpositionen','___ casa es grande. (bestimmter Artikel)',['La','El','Los','Las'],'La','„casa“ ist weiblich und Einzahl: „la casa“.','Das Haus ist groß.','La casa es grande.'],
['Artikel & Präpositionen','___ libro es nuevo. (bestimmter Artikel)',['El','La','Los','Las'],'El','„libro“ ist männlich und Einzahl: „el libro“.','Das Buch ist neu.','El libro es nuevo.'],
['Artikel & Präpositionen','Tengo ___ perro. (unbestimmter Artikel)',['un','una','unos','unas'],'un','„perro“ ist männlich und Einzahl: „un perro“.','Ich habe einen Hund.','Tengo un perro.'],
['Artikel & Präpositionen','Tengo ___ manzana. (unbestimmter Artikel)',['un','una','unos','unas'],'una','„manzana“ ist weiblich und Einzahl: „una manzana“.','Ich habe einen Apfel.','Tengo una manzana.'],
['Artikel & Präpositionen','___ niños juegan. (bestimmter Artikel)',['Los','Las','El','La'],'Los','„niños“ ist männlich und Mehrzahl: „los niños“.','Die Jungen spielen.','Los niños juegan.'],
['Artikel & Präpositionen','___ niñas cantan. (bestimmter Artikel)',['Las','Los','El','La'],'Las','„niñas“ ist weiblich und Mehrzahl: „las niñas“.','Die Mädchen singen.','Las niñas cantan.'],
['Artikel & Präpositionen','Vivo ___ España.',['en','a','de','con'],'en','Für einen Wohnort verwendet man hier „en“.','Ich wohne in Spanien.','Vivo en España.'],
['Artikel & Präpositionen','Voy ___ Madrid.',['a','en','de','con'],'a','Eine Bewegung nach Madrid wird hier mit „a“ ausgedrückt.','Ich fahre nach Madrid.','Voy a Madrid.'],
['Artikel & Präpositionen','Soy ___ Alemania.',['de','a','en','con'],'de','Für die Herkunft verwendet man „de“.','Ich komme aus Deutschland.','Soy de Alemania.'],
['Artikel & Präpositionen','Hablo ___ mi hermana.',['con','a','de','en'],'con','Mit jemandem sprechen heißt „hablar con“.','Ich spreche mit meiner Schwester.','Hablo con mi hermana.'],
['Artikel & Präpositionen','El gato está ___ la mesa. (darunter)',['debajo de','en','sobre','con'],'debajo de','„debajo de“ bedeutet „unter“.','Die Katze ist unter dem Tisch.','El gato está debajo de la mesa.'],
['Artikel & Präpositionen','Regreso ___ casa.',['a','en','de','por'],'a','„Nach Hause zurückkehren“ heißt „regresar a casa“.','Ich kehre nach Hause zurück.','Regreso a casa.'],
['Artikel & Präpositionen','Salgo ___ mi amigo. (zusammen)',['con','de','a','por'],'con','„Zusammen mit“ heißt hier „con“.','Ich gehe mit meinem Freund aus.','Salgo con mi amigo.'],
['Artikel & Präpositionen','La reunión es ___ lunes.',['el','en','a','de'],'el','Für einen bestimmten Wochentag verwendet man hier „el“.','Das Treffen ist am Montag.','La reunión es el lunes.'],
['Artikel & Präpositionen','Voy ___ cine.',['al','en','del','con'],'al','„a“ und „el“ verschmelzen zu „al“.','Ich gehe ins Kino.','Voy al cine.'],
['Artikel & Präpositionen','Vengo ___ trabajo. (von der Arbeit)',['del','al','en','con'],'del','„de“ und „el“ verschmelzen zu „del“.','Ich komme von der Arbeit.','Vengo del trabajo.'],
['Artikel & Präpositionen','Este regalo es ___ ti.',['para','por','de','a'],'para','Ein Geschenk für jemanden: „para ti“.','Dieses Geschenk ist für dich.','Este regalo es para ti.'],
['Artikel & Präpositionen','Estoy ___ casa.',['en','a','de','con'],'en','„Zu Hause sein“ heißt „estar en casa“.','Ich bin zu Hause.','Estoy en casa.'],
['Artikel & Präpositionen','El libro es ___ Ana.',['de','a','en','con'],'de','Besitz wird hier mit „de“ ausgedrückt.','Das Buch gehört Ana.','El libro es de Ana.'],
['Artikel & Präpositionen','Voy ___ autobús.',['en','por','de','a'],'en','Das Verkehrsmittel wird hier mit „en“ ausgedrückt.','Ich fahre mit dem Bus.','Voy en autobús.']
].map(([category,prompt,options,answer,explanation,de,target])=>({category,prompt,options,answer,explanation,de,target}));
