window.TRAINER_I18N={
 "texts": {
  "de": {
   "title": "Sprachtrainer",
   "uiLanguage": "Menü- und Basissprache",
   "language": "Sprache",
   "choose": "Welche Sprache möchtest du mit {base} üben?",
   "menu": "Was möchtest du zwischen {de} und {language} üben?",
   "next": "Weiter →",
   "languagesBack": "← Sprachauswahl",
   "modesBack": "← Übungsarten",
   "words": "📚 Wörter",
   "wordsDesc": "Vokabeln üben",
   "sentences": "💬 Sätze",
   "sentencesDesc": "Alltagssituationen üben",
   "grammar": "✏️ Grammatik",
   "grammarDesc": "Formen verstehen und üben",
   "topic": "Thema",
   "situation": "Situation",
   "direction": "Richtung",
   "start": "Lernen starten",
   "setupWords": "In welche Richtung möchtest du üben?",
   "setupSentences": "Welche Sätze möchtest du üben?",
   "setupGrammar": "Welches Grammatikthema möchtest du üben?",
   "allSituations": "Alle Situationen",
   "allTopics": "Alle Themen",
   "listen": "🔊 {language} anhören",
   "stats": "{score} richtig von {answered}",
   "correct": "Richtig!",
   "solution": "Richtig ist: {answer}",
   "example": "Beispielsatz:",
   "finish": "Runde beenden · Fehler ansehen",
   "reviewTitle": "Rundenauswertung",
   "reviewStats": "{score} richtig von {answered} Antworten · {mistakes} verschiedene Aufgaben falsch beantwortet",
   "noMistakes": "Keine Fehler in dieser Runde.",
   "yourAnswer": "Deine Antwort:",
   "wrongCount": "{count}× falsch",
   "recovered": "später richtig",
   "repeat": "Fehler wiederholen",
   "newRound": "Neue Runde",
   "speechError": "Sprachausgabe wird von diesem Browser nicht unterstützt.",
   "sentenceError": "Die Sätze konnten nicht geladen werden. Bitte prüfe die hochgeladenen Dateien.",
   "grammarError": "Die Grammatikübungen konnten nicht geladen werden. Bitte prüfe die hochgeladenen Dateien.",
   "startError": "Die Übung konnte nicht gestartet werden. Bitte prüfe die Dateien und versuche es erneut.",
   "de": "Deutsch",
   "en": "Englisch",
   "fr": "Französisch",
   "es": "Spanisch",
   "it": "Italienisch",
   "pl": "Polnisch"
  },
  "en": {
   "title": "Language trainer",
   "uiLanguage": "Interface and base language",
   "language": "Language",
   "choose": "Which language would you like to practise with {base}?",
   "menu": "What would you like to practise between {de} and {language}?",
   "next": "Next →",
   "languagesBack": "← Language selection",
   "modesBack": "← Exercise types",
   "words": "📚 Words",
   "wordsDesc": "Practise vocabulary",
   "sentences": "💬 Sentences",
   "sentencesDesc": "Practise everyday situations",
   "grammar": "✏️ Grammar",
   "grammarDesc": "Understand and practise forms",
   "topic": "Topic",
   "situation": "Situation",
   "direction": "Direction",
   "start": "Start practising",
   "setupWords": "Which direction would you like to practise?",
   "setupSentences": "Which sentences would you like to practise?",
   "setupGrammar": "Which grammar topic would you like to practise?",
   "allSituations": "All situations",
   "allTopics": "All topics",
   "listen": "🔊 Listen: {language}",
   "stats": "{score} correct out of {answered}",
   "correct": "Correct!",
   "solution": "Correct answer: {answer}",
   "example": "Example sentence:",
   "finish": "End session · Review mistakes",
   "reviewTitle": "Session review",
   "reviewStats": "{score} correct out of {answered} answers · {mistakes} different exercises answered incorrectly",
   "noMistakes": "No mistakes in this session.",
   "yourAnswer": "Your answer:",
   "wrongCount": "{count}× incorrect",
   "recovered": "correct later",
   "repeat": "Repeat mistakes",
   "newRound": "New session",
   "speechError": "This browser does not support speech output.",
   "sentenceError": "Sentences could not be loaded. Please check the uploaded files.",
   "grammarError": "Grammar exercises could not be loaded. Please check the uploaded files.",
   "startError": "The exercise could not start. Check the files and try again.",
   "de": "German",
   "en": "English",
   "fr": "French",
   "es": "Spanish",
   "it": "Italian",
   "pl": "Polish"
  },
  "fr": {
   "title": "Entraînement linguistique",
   "uiLanguage": "Langue de l’interface et langue de base",
   "language": "Langue",
   "choose": "Quelle langue souhaitez-vous pratiquer avec {base} ?",
   "menu": "Que souhaitez-vous pratiquer entre {de} et {language} ?",
   "next": "Suivant →",
   "languagesBack": "← Choix de la langue",
   "modesBack": "← Types d’exercices",
   "words": "📚 Mots",
   "wordsDesc": "Pratiquer le vocabulaire",
   "sentences": "💬 Phrases",
   "sentencesDesc": "Pratiquer des situations quotidiennes",
   "grammar": "✏️ Grammaire",
   "grammarDesc": "Comprendre et pratiquer les formes",
   "topic": "Thème",
   "situation": "Situation",
   "direction": "Sens",
   "start": "Commencer",
   "setupWords": "Dans quel sens souhaitez-vous pratiquer ?",
   "setupSentences": "Quelles phrases souhaitez-vous pratiquer ?",
   "setupGrammar": "Quel thème de grammaire souhaitez-vous pratiquer ?",
   "allSituations": "Toutes les situations",
   "allTopics": "Tous les thèmes",
   "listen": "🔊 Écouter : {language}",
   "stats": "{score} bonnes réponses sur {answered}",
   "correct": "Correct !",
   "solution": "Bonne réponse : {answer}",
   "example": "Phrase d’exemple :",
   "finish": "Terminer · Voir les erreurs",
   "reviewTitle": "Bilan de la session",
   "reviewStats": "{score} bonnes réponses sur {answered} · {mistakes} exercices différents avec une erreur",
   "noMistakes": "Aucune erreur dans cette session.",
   "yourAnswer": "Votre réponse :",
   "wrongCount": "{count}× incorrect",
   "recovered": "réussi ensuite",
   "repeat": "Reprendre les erreurs",
   "newRound": "Nouvelle session",
   "speechError": "Ce navigateur ne prend pas en charge la synthèse vocale.",
   "sentenceError": "Impossible de charger les phrases. Vérifiez les fichiers importés.",
   "grammarError": "Impossible de charger les exercices de grammaire. Vérifiez les fichiers importés.",
   "startError": "Impossible de démarrer l’exercice. Vérifiez les fichiers et réessayez.",
   "de": "Allemand",
   "en": "Anglais",
   "fr": "Français",
   "es": "Espagnol",
   "it": "Italien",
   "pl": "Polonais"
  },
  "es": {
   "title": "Entrenador de idiomas",
   "uiLanguage": "Idioma de la interfaz y de base",
   "language": "Idioma",
   "choose": "¿Qué idioma quieres practicar con {base}?",
   "menu": "¿Qué quieres practicar entre {de} y {language}?",
   "next": "Siguiente →",
   "languagesBack": "← Selección de idioma",
   "modesBack": "← Tipos de ejercicios",
   "words": "📚 Palabras",
   "wordsDesc": "Practicar vocabulario",
   "sentences": "💬 Frases",
   "sentencesDesc": "Practicar situaciones cotidianas",
   "grammar": "✏️ Gramática",
   "grammarDesc": "Comprender y practicar las formas",
   "topic": "Tema",
   "situation": "Situación",
   "direction": "Dirección",
   "start": "Empezar a practicar",
   "setupWords": "¿En qué dirección quieres practicar?",
   "setupSentences": "¿Qué frases quieres practicar?",
   "setupGrammar": "¿Qué tema de gramática quieres practicar?",
   "allSituations": "Todas las situaciones",
   "allTopics": "Todos los temas",
   "listen": "🔊 Escuchar: {language}",
   "stats": "{score} correctas de {answered}",
   "correct": "¡Correcto!",
   "solution": "Respuesta correcta: {answer}",
   "example": "Frase de ejemplo:",
   "finish": "Terminar · Ver errores",
   "reviewTitle": "Resultados de la sesión",
   "reviewStats": "{score} correctas de {answered} respuestas · {mistakes} ejercicios distintos con errores",
   "noMistakes": "No hubo errores en esta sesión.",
   "yourAnswer": "Tu respuesta:",
   "wrongCount": "{count}× incorrecta",
   "recovered": "correcta después",
   "repeat": "Repetir errores",
   "newRound": "Nueva sesión",
   "speechError": "Este navegador no admite la síntesis de voz.",
   "sentenceError": "No se pudieron cargar las frases. Revisa los archivos subidos.",
   "grammarError": "No se pudieron cargar los ejercicios de gramática. Revisa los archivos subidos.",
   "startError": "No se pudo iniciar el ejercicio. Revisa los archivos e inténtalo de nuevo.",
   "de": "Alemán",
   "en": "Inglés",
   "fr": "Francés",
   "es": "Español",
   "it": "Italiano",
   "pl": "Polaco"
  },
  "it": {
   "title": "Allenamento linguistico",
   "uiLanguage": "Lingua dell’interfaccia e di base",
   "language": "Lingua",
   "choose": "Quale lingua vuoi esercitare insieme a {base}?",
   "menu": "Cosa vuoi esercitare tra {de} e {language}?",
   "next": "Avanti →",
   "languagesBack": "← Scelta della lingua",
   "modesBack": "← Tipi di esercizi",
   "words": "📚 Parole",
   "wordsDesc": "Esercitare il vocabolario",
   "sentences": "💬 Frasi",
   "sentencesDesc": "Esercitare situazioni quotidiane",
   "grammar": "✏️ Grammatica",
   "grammarDesc": "Capire ed esercitare le forme",
   "topic": "Argomento",
   "situation": "Situazione",
   "direction": "Direzione",
   "start": "Inizia a esercitarti",
   "setupWords": "In quale direzione vuoi esercitarti?",
   "setupSentences": "Quali frasi vuoi esercitare?",
   "setupGrammar": "Quale argomento di grammatica vuoi esercitare?",
   "allSituations": "Tutte le situazioni",
   "allTopics": "Tutti gli argomenti",
   "listen": "🔊 Ascolta: {language}",
   "stats": "{score} corrette su {answered}",
   "correct": "Corretto!",
   "solution": "Risposta corretta: {answer}",
   "example": "Frase di esempio:",
   "finish": "Termina · Vedi gli errori",
   "reviewTitle": "Risultati della sessione",
   "reviewStats": "{score} corrette su {answered} risposte · {mistakes} esercizi diversi con errori",
   "noMistakes": "Nessun errore in questa sessione.",
   "yourAnswer": "La tua risposta:",
   "wrongCount": "{count}× errata",
   "recovered": "corretta in seguito",
   "repeat": "Ripeti gli errori",
   "newRound": "Nuova sessione",
   "speechError": "Questo browser non supporta la sintesi vocale.",
   "sentenceError": "Impossibile caricare le frasi. Controlla i file caricati.",
   "grammarError": "Impossibile caricare gli esercizi di grammatica. Controlla i file caricati.",
   "startError": "Impossibile avviare l’esercizio. Controlla i file e riprova.",
   "de": "Tedesco",
   "en": "Inglese",
   "fr": "Francese",
   "es": "Spagnolo",
   "it": "Italiano",
   "pl": "Polacco"
  },
  "pl": {
   "title": "Trener językowy",
   "uiLanguage": "Język interfejsu i język bazowy",
   "language": "Język",
   "choose": "Jaki język chcesz ćwiczyć w parze z językiem {base}?",
   "menu": "Co chcesz ćwiczyć w parze języków {de} i {language}?",
   "next": "Dalej →",
   "languagesBack": "← Wybór języka",
   "modesBack": "← Rodzaje ćwiczeń",
   "words": "📚 Słowa",
   "wordsDesc": "Ćwicz słownictwo",
   "sentences": "💬 Zdania",
   "sentencesDesc": "Ćwicz codzienne sytuacje",
   "grammar": "✏️ Gramatyka",
   "grammarDesc": "Poznaj i ćwicz formy gramatyczne",
   "topic": "Temat",
   "situation": "Sytuacja",
   "direction": "Kierunek",
   "start": "Rozpocznij ćwiczenie",
   "setupWords": "W którym kierunku chcesz ćwiczyć?",
   "setupSentences": "Jakie zdania chcesz ćwiczyć?",
   "setupGrammar": "Jaki temat gramatyczny chcesz ćwiczyć?",
   "allSituations": "Wszystkie sytuacje",
   "allTopics": "Wszystkie tematy",
   "listen": "🔊 Posłuchaj: {language}",
   "stats": "Poprawne: {score} z {answered}",
   "correct": "Dobrze!",
   "solution": "Poprawna odpowiedź: {answer}",
   "example": "Przykładowe zdanie:",
   "finish": "Zakończ rundę · Zobacz błędy",
   "reviewTitle": "Podsumowanie rundy",
   "reviewStats": "Poprawne: {score} z {answered} odpowiedzi · Różne zadania z błędem: {mistakes}",
   "noMistakes": "Brak błędów w tej rundzie.",
   "yourAnswer": "Twoja odpowiedź:",
   "wrongCount": "Błędnie: {count}×",
   "recovered": "później poprawnie",
   "repeat": "Powtórz błędne zadania",
   "newRound": "Nowa runda",
   "speechError": "Ta przeglądarka nie obsługuje syntezy mowy.",
   "sentenceError": "Nie udało się wczytać zdań. Sprawdź przesłane pliki.",
   "grammarError": "Nie udało się wczytać ćwiczeń gramatycznych. Sprawdź przesłane pliki.",
   "startError": "Nie udało się rozpocząć ćwiczenia. Sprawdź pliki i spróbuj ponownie.",
   "de": "Niemiecki",
   "en": "Angielski",
   "fr": "Francuski",
   "es": "Hiszpański",
   "it": "Włoski",
   "pl": "Polski"
  }
 },
 "categories": {
  "de": {
   "Adjektivformen": "Adjektivformen",
   "Alltag": "Alltag",
   "Artikel & Präpositionen": "Artikel & Präpositionen",
   "Artikel und Pronomen": "Artikel und Pronomen",
   "Begrüßung": "Begrüßung",
   "Eigenschaften": "Eigenschaften",
   "Einkaufen": "Einkaufen",
   "Essen & Trinken": "Essen & Trinken",
   "Familie": "Familie",
   "Familie & Alltag": "Familie & Alltag",
   "Fragen": "Fragen",
   "Fälle": "Fälle",
   "Gesundheit": "Gesundheit",
   "Im Café": "Im Café",
   "Im Hotel": "Im Hotel",
   "Kleidung": "Kleidung",
   "Menschen": "Menschen",
   "Orte": "Orte",
   "Präpositionen und Wortformen": "Präpositionen und Wortformen",
   "Reisen": "Reisen",
   "Unterwegs": "Unterwegs",
   "Verbformen": "Verbformen",
   "Vergangenheit": "Vergangenheit",
   "Wohnen": "Wohnen",
   "Zahlen": "Zahlen",
   "Zeit": "Zeit",
   "Zeitformen": "Zeitformen"
  },
  "en": {
   "Adjektivformen": "Adjective forms",
   "Alltag": "Everyday life",
   "Artikel & Präpositionen": "Articles and prepositions",
   "Artikel und Pronomen": "Articles and pronouns",
   "Begrüßung": "Greetings",
   "Eigenschaften": "Qualities",
   "Einkaufen": "Shopping",
   "Essen & Trinken": "Food and drink",
   "Familie": "Family",
   "Familie & Alltag": "Family and everyday life",
   "Fragen": "Questions",
   "Fälle": "Cases",
   "Gesundheit": "Health",
   "Im Café": "At the café",
   "Im Hotel": "At the hotel",
   "Kleidung": "Clothing",
   "Menschen": "People",
   "Orte": "Places",
   "Präpositionen und Wortformen": "Prepositions and word forms",
   "Reisen": "Travel",
   "Unterwegs": "Getting around",
   "Verbformen": "Verb forms",
   "Vergangenheit": "Past tense",
   "Wohnen": "Home",
   "Zahlen": "Numbers",
   "Zeit": "Time",
   "Zeitformen": "Tenses"
  },
  "fr": {
   "Adjektivformen": "Formes des adjectifs",
   "Alltag": "Vie quotidienne",
   "Artikel & Präpositionen": "Articles et prépositions",
   "Artikel und Pronomen": "Articles et pronoms",
   "Begrüßung": "Salutations",
   "Eigenschaften": "Qualités",
   "Einkaufen": "Achats",
   "Essen & Trinken": "Nourriture et boissons",
   "Familie": "Famille",
   "Familie & Alltag": "Famille et quotidien",
   "Fragen": "Questions",
   "Fälle": "Cas grammaticaux",
   "Gesundheit": "Santé",
   "Im Café": "Au café",
   "Im Hotel": "À l’hôtel",
   "Kleidung": "Vêtements",
   "Menschen": "Personnes",
   "Orte": "Lieux",
   "Präpositionen und Wortformen": "Prépositions et formes des mots",
   "Reisen": "Voyages",
   "Unterwegs": "En déplacement",
   "Verbformen": "Formes verbales",
   "Vergangenheit": "Passé",
   "Wohnen": "Logement",
   "Zahlen": "Nombres",
   "Zeit": "Temps",
   "Zeitformen": "Temps verbaux"
  },
  "es": {
   "Adjektivformen": "Formas de adjetivos",
   "Alltag": "Vida cotidiana",
   "Artikel & Präpositionen": "Artículos y preposiciones",
   "Artikel und Pronomen": "Artículos y pronombres",
   "Begrüßung": "Saludos",
   "Eigenschaften": "Cualidades",
   "Einkaufen": "Compras",
   "Essen & Trinken": "Comida y bebida",
   "Familie": "Familia",
   "Familie & Alltag": "Familia y vida cotidiana",
   "Fragen": "Preguntas",
   "Fälle": "Casos gramaticales",
   "Gesundheit": "Salud",
   "Im Café": "En la cafetería",
   "Im Hotel": "En el hotel",
   "Kleidung": "Ropa",
   "Menschen": "Personas",
   "Orte": "Lugares",
   "Präpositionen und Wortformen": "Preposiciones y formas de palabras",
   "Reisen": "Viajes",
   "Unterwegs": "Desplazamientos",
   "Verbformen": "Formas verbales",
   "Vergangenheit": "Pasado",
   "Wohnen": "Vivienda",
   "Zahlen": "Números",
   "Zeit": "Tiempo",
   "Zeitformen": "Tiempos verbales"
  },
  "it": {
   "Adjektivformen": "Forme degli aggettivi",
   "Alltag": "Vita quotidiana",
   "Artikel & Präpositionen": "Articoli e preposizioni",
   "Artikel und Pronomen": "Articoli e pronomi",
   "Begrüßung": "Saluti",
   "Eigenschaften": "Qualità",
   "Einkaufen": "Acquisti",
   "Essen & Trinken": "Cibo e bevande",
   "Familie": "Famiglia",
   "Familie & Alltag": "Famiglia e vita quotidiana",
   "Fragen": "Domande",
   "Fälle": "Casi grammaticali",
   "Gesundheit": "Salute",
   "Im Café": "Al bar",
   "Im Hotel": "In hotel",
   "Kleidung": "Abbigliamento",
   "Menschen": "Persone",
   "Orte": "Luoghi",
   "Präpositionen und Wortformen": "Preposizioni e forme delle parole",
   "Reisen": "Viaggi",
   "Unterwegs": "In viaggio",
   "Verbformen": "Forme verbali",
   "Vergangenheit": "Passato",
   "Wohnen": "Abitare",
   "Zahlen": "Numeri",
   "Zeit": "Tempo",
   "Zeitformen": "Tempi verbali"
  },
  "pl": {
   "Adjektivformen": "Formy przymiotników",
   "Alltag": "Życie codzienne",
   "Artikel & Präpositionen": "Rodzajniki i przyimki",
   "Artikel und Pronomen": "Rodzajniki i zaimki",
   "Begrüßung": "Powitania",
   "Eigenschaften": "Cechy",
   "Einkaufen": "Zakupy",
   "Essen & Trinken": "Jedzenie i picie",
   "Familie": "Rodzina",
   "Familie & Alltag": "Rodzina i życie codzienne",
   "Fragen": "Pytania",
   "Fälle": "Przypadki",
   "Gesundheit": "Zdrowie",
   "Im Café": "W kawiarni",
   "Im Hotel": "W hotelu",
   "Kleidung": "Ubrania",
   "Menschen": "Ludzie",
   "Orte": "Miejsca",
   "Präpositionen und Wortformen": "Przyimki i formy wyrazów",
   "Reisen": "Podróże",
   "Unterwegs": "W drodze",
   "Verbformen": "Formy czasowników",
   "Vergangenheit": "Czas przeszły",
   "Wohnen": "Mieszkanie",
   "Zahlen": "Liczby",
   "Zeit": "Czas",
   "Zeitformen": "Czasy gramatyczne"
  }
 }
};
let uiLanguage='de';
try{const saved=localStorage.getItem('trainer-ui-language');if(window.TRAINER_I18N.texts[saved])uiLanguage=saved}catch(e){}
function t(key,params={}){let value=window.TRAINER_I18N.texts[uiLanguage][key]??window.TRAINER_I18N.texts.de[key]??key;return value.replace(/\{(\w+)\}/g,(_,name)=>params[name]??'{'+name+'}')}
function categoryName(category){return window.TRAINER_I18N.categories[uiLanguage][category]??category}
function languageName(id){return t(id)}
