window.TRAINER_I18N={
 "texts": {
  "de": {
   "title": "Sprachtrainer",
   "uiLanguage": "Menü- und Basissprache",
   "language": "Sprache",
   "choose": "Welche Sprache möchtest du mit {base} üben?",
   "menu": "Was möchtest du zwischen {de} und {language} üben?",
   "next": "Weiter →",
   "languagesBack": "← Sprachauswahl",
   "modesBack": "← Übungsarten",
   "words": "📚 Wörter",
   "wordsDesc": "Vokabeln üben",
   "sentences": "💬 Sätze",
   "sentencesDesc": "Alltagssituationen üben",
   "grammar": "✏️ Grammatik",
   "grammarDesc": "Formen verstehen und üben",
   "topic": "Thema",
   "situation": "Situation",
   "direction": "Richtung",
   "start": "Lernen starten",
   "setupWords": "In welche Richtung möchtest du üben?",
   "setupSentences": "Welche Sätze möchtest du üben?",
   "setupGrammar": "Welches Grammatikthema möchtest du üben?",
   "allSituations": "Alle Situationen",
   "allTopics": "Alle Themen",
   "listen": "🔊 {language} anhören",
   "stats": "{score} richtig von {answered}",
   "correct": "Richtig!",
   "solution": "Richtig ist: {answer}",
   "example": "Beispielsatz:",
   "finish": "Runde beenden · Fehler ansehen",
   "reviewTitle": "Rundenauswertung",
   "reviewStats": "{score} richtig von {answered} Antworten · {mistakes} verschiedene Aufgaben falsch beantwortet",
   "noMistakes": "Keine Fehler in dieser Runde.",
   "yourAnswer": "Deine Antwort:",
   "wrongCount": "{count}× falsch",
   "recovered": "später richtig",
   "repeat": "Fehler wiederholen",
   "newRound": "Neue Runde",
   "speechError": "Sprachausgabe wird von diesem Browser nicht unterstützt.",
   "sentenceError": "Die Sätze konnten nicht geladen werden. Bitte prüfe die hochgeladenen Dateien.",
   "grammarError": "Die Grammatikübungen konnten nicht geladen werden. Bitte prüfe die hochgeladenen Dateien.",
   "startError": "Die Übung konnte nicht gestartet werden. Bitte prüfe die Dateien und versuche es erneut.",
   "de": "Deutsch",
   "en": "Englisch",
   "fr": "Französisch",
   "es": "Spanisch",
   "it": "Italienisch",
   "pl": "Polnisch",
   "testVersion": "🧪 Konten-Testversion",
   "oldTrainer": "Zum bisherigen Trainer",
   "guestLabel": "Gast · Ergebnisse nur in dieser Runde",
   "signedIn": "Angemeldet: {name}",
   "learner": "Lernender",
   "accountName": "Name (optional)",
   "accountEmail": "E-Mail",
   "accountPassword": "Passwort",
   "accountLogin": "Anmelden",
   "accountSignup": "Konto anlegen",
   "accountLogout": "Abmelden",
   "accountSync": "Synchronisieren",
   "progressOpen": "Mein gespeicherter Lernstand",
   "progressTitle": "Mein Lernstand",
   "savedErrors": "Gespeicherte Fehler üben",
   "noPairAnswers": "Noch keine gespeicherten Antworten für {base} ↔ {target}. Starte eine Übung.",
   "progressWords": "Wörter",
   "progressSentences": "Sätze",
   "progressGrammar": "Grammatik",
   "progressStats": "{mode}: {correct} von {total} Antworten richtig · {tasks} Aufgaben/Richtungen bearbeitet · {errors} offene Fehler",
   "syncPending": "{count} Antworten warten auf Übertragung.",
   "syncDone": "Lernstand mit der Datenbank synchronisiert.",
   "syncOffline": "Verbindung nicht möglich. Nicht übertragene Antworten bleiben auf diesem Gerät vorgemerkt. Nutze später „Synchronisieren“.",
   "syncStorageError": "Speichern derzeit nicht möglich. Lass die Seite geöffnet und versuche „Synchronisieren“ erneut.",
   "progressLoading": "Lernstand wird geladen …",
   "guestStatus": "Als Gast kannst du weiter üben.",
   "answerSaving": "Antwort wird gespeichert …",
   "answerOnline": "Lokaler Speicher nicht verfügbar. Antwort wird online übertragen …",
   "confirmSignup": "Falls die Registrierung möglich ist, erhältst du eine Bestätigungs-E-Mail. Öffne den Link und melde dich danach hier an.",
   "invalidLogin": "E-Mail oder Passwort stimmt nicht.",
   "emailUnconfirmed": "Bitte bestätige zuerst den Link in deiner E-Mail.",
   "accountError": "Das Konto konnte nicht verarbeitet werden. Prüfe deine Angaben und versuche es erneut. Bei E-Mail-Limits bitte später erneut versuchen.",
   "logoutError": "Abmelden nicht möglich. Bitte erneut versuchen.",
   "accountsUnconfigured": "Konten sind noch nicht verbunden. Die Testversion lässt sich als Gast ausprobieren.",
   "accountConfigError": "Konfiguration prüfen: Projekt-URL und öffentlicher Publishable Key erforderlich.",
   "accountWelcome": "Melde dich an oder lege ein Testkonto an.",
   "accountUnavailable": "Kontoverbindung nicht verfügbar. Du kannst als Gast üben.",
   "noSavedErrors": "Keine offenen gespeicherten Fehler für diese Auswahl.",
   "savedErrorsError": "Gespeicherte Fehler konnten nicht gestartet werden."
  },
  "en": {
   "title": "Language trainer",
   "uiLanguage": "Interface and base language",
   "language": "Language",
   "choose": "Which language would you like to practise with {base}?",
   "menu": "What would you like to practise between {de} and {language}?",
   "next": "Next →",
   "languagesBack": "← Language selection",
   "modesBack": "← Exercise types",
   "words": "📚 Words",
   "wordsDesc": "Practise vocabulary",
   "sentences": "💬 Sentences",
   "sentencesDesc": "Practise everyday situations",
   "grammar": "✏️ Grammar",
   "grammarDesc": "Understand and practise forms",
   "topic": "Topic",
   "situation": "Situation",
   "direction": "Direction",
   "start": "Start practising",
   "setupWords": "Which direction would you like to practise?",
   "setupSentences": "Which sentences would you like to practise?",
   "setupGrammar": "Which grammar topic would you like to practise?",
   "allSituations": "All situations",
   "allTopics": "All topics",
   "listen": "🔊 Listen: {language}",
   "stats": "{score} correct out of {answered}",
   "correct": "Correct!",
   "solution": "Correct answer: {answer}",
   "example": "Example sentence:",
   "finish": "End session · Review mistakes",
   "reviewTitle": "Session review",
   "reviewStats": "{score} correct out of {answered} answers · {mistakes} different exercises answered incorrectly",
   "noMistakes": "No mistakes in this session.",
   "yourAnswer": "Your answer:",
   "wrongCount": "{count}× incorrect",
   "recovered": "correct later",
   "repeat": "Repeat mistakes",
   "newRound": "New session",
   "speechError": "This browser does not support speech output.",
   "sentenceError": "Sentences could not be loaded. Please check the uploaded files.",
   "grammarError": "Grammar exercises could not be loaded. Please check the uploaded files.",
   "startError": "The exercise could not start. Check the files and try again.",
   "de": "German",
   "en": "English",
   "fr": "French",
   "es": "Spanish",
   "it": "Italian",
   "pl": "Polish",
   "testVersion": "🧪 Account test version",
   "oldTrainer": "Open the original trainer",
   "guestLabel": "Guest · Results for this round only",
   "signedIn": "Signed in: {name}",
   "learner": "Learner",
   "accountName": "Name (optional)",
   "accountEmail": "Email",
   "accountPassword": "Password",
   "accountLogin": "Sign in",
   "accountSignup": "Create account",
   "accountLogout": "Sign out",
   "accountSync": "Synchronize",
   "progressOpen": "My saved progress",
   "progressTitle": "My progress",
   "savedErrors": "Practice saved mistakes",
   "noPairAnswers": "No saved answers for {base} ↔ {target} yet. Start an exercise.",
   "progressWords": "Words",
   "progressSentences": "Sentences",
   "progressGrammar": "Grammar",
   "progressStats": "{mode}: {correct} of {total} answers correct · {tasks} tasks/directions practiced · {errors} unresolved mistakes",
   "syncPending": "{count} answers are waiting to be uploaded.",
   "syncDone": "Progress synchronized with the database.",
   "syncOffline": "Unable to connect. Answers not uploaded remain queued on this device. Use “Synchronize” later.",
   "syncStorageError": "Unable to save right now. Keep the page open and try “Synchronize” again.",
   "progressLoading": "Loading progress …",
   "guestStatus": "You can keep practicing as a guest.",
   "answerSaving": "Saving answer …",
   "answerOnline": "Local storage is unavailable. Uploading answer …",
   "confirmSignup": "If registration is possible, you will receive a confirmation email. Open the link, then sign in here.",
   "invalidLogin": "Incorrect email or password.",
   "emailUnconfirmed": "Please confirm your email using the link first.",
   "accountError": "Unable to process the account. Check your details and try again. If an email limit applies, try again later.",
   "logoutError": "Unable to sign out. Please try again.",
   "accountsUnconfigured": "Accounts are not connected yet. You can try the test version as a guest.",
   "accountConfigError": "Check configuration: project URL and public publishable key are required.",
   "accountWelcome": "Sign in or create a test account.",
   "accountUnavailable": "Account connection unavailable. You can practice as a guest.",
   "noSavedErrors": "No unresolved saved mistakes for this selection.",
   "savedErrorsError": "Unable to start practicing saved mistakes."
  },
  "fr": {
   "title": "Entraînement linguistique",
   "uiLanguage": "Langue de l’interface et langue de base",
   "language": "Langue",
   "choose": "Quelle langue souhaitez-vous pratiquer avec {base} ?",
   "menu": "Que souhaitez-vous pratiquer entre {de} et {language} ?",
   "next": "Suivant →",
   "languagesBack": "← Choix de la langue",
   "modesBack": "← Types d’exercices",
   "words": "📚 Mots",
   "wordsDesc": "Pratiquer le vocabulaire",
   "sentences": "💬 Phrases",
   "sentencesDesc": "Pratiquer des situations quotidiennes",
   "grammar": "✏️ Grammaire",
   "grammarDesc": "Comprendre et pratiquer les formes",
   "topic": "Thème",
   "situation": "Situation",
   "direction": "Sens",
   "start": "Commencer",
   "setupWords": "Dans quel sens souhaitez-vous pratiquer ?",
   "setupSentences": "Quelles phrases souhaitez-vous pratiquer ?",
   "setupGrammar": "Quel thème de grammaire souhaitez-vous pratiquer ?",
   "allSituations": "Toutes les situations",
   "allTopics": "Tous les thèmes",
   "listen": "🔊 Écouter : {language}",
   "stats": "{score} bonnes réponses sur {answered}",
   "correct": "Correct !",
   "solution": "Bonne réponse : {answer}",
   "example": "Phrase d’exemple :",
   "finish": "Terminer · Voir les erreurs",
   "reviewTitle": "Bilan de la session",
   "reviewStats": "{score} bonnes réponses sur {answered} · {mistakes} exercices différents avec une erreur",
   "noMistakes": "Aucune erreur dans cette session.",
   "yourAnswer": "Votre réponse :",
   "wrongCount": "{count}× incorrect",
   "recovered": "réussi ensuite",
   "repeat": "Reprendre les erreurs",
   "newRound": "Nouvelle session",
   "speechError": "Ce navigateur ne prend pas en charge la synthèse vocale.",
   "sentenceError": "Impossible de charger les phrases. Vérifiez les fichiers importés.",
   "grammarError": "Impossible de charger les exercices de grammaire. Vérifiez les fichiers importés.",
   "startError": "Impossible de démarrer l’exercice. Vérifiez les fichiers et réessayez.",
   "de": "Allemand",
   "en": "Anglais",
   "fr": "Français",
   "es": "Espagnol",
   "it": "Italien",
   "pl": "Polonais",
   "testVersion": "🧪 Version de test des comptes",
   "oldTrainer": "Ouvrir le site d’apprentissage habituel",
   "guestLabel": "Invité · Résultats de cette session uniquement",
   "signedIn": "Connecté : {name}",
   "learner": "Apprenant",
   "accountName": "Nom (facultatif)",
   "accountEmail": "Adresse e-mail",
   "accountPassword": "Mot de passe",
   "accountLogin": "Se connecter",
   "accountSignup": "Créer un compte",
   "accountLogout": "Se déconnecter",
   "accountSync": "Synchroniser",
   "progressOpen": "Ma progression enregistrée",
   "progressTitle": "Ma progression",
   "savedErrors": "Revoir les erreurs enregistrées",
   "noPairAnswers": "Aucune réponse enregistrée pour {base} ↔ {target}. Commencez un exercice.",
   "progressWords": "Mots",
   "progressSentences": "Phrases",
   "progressGrammar": "Grammaire",
   "progressStats": "{mode} : {correct} réponses correctes sur {total} · {tasks} exercices/sens pratiqués · {errors} erreurs à revoir",
   "syncPending": "{count} réponses sont en attente d’envoi.",
   "syncDone": "Progression synchronisée avec la base de données.",
   "syncOffline": "Connexion impossible. Les réponses non envoyées restent en attente sur cet appareil. Utilisez « Synchroniser » plus tard.",
   "syncStorageError": "Enregistrement impossible pour le moment. Gardez la page ouverte et réessayez avec « Synchroniser ».",
   "progressLoading": "Chargement de la progression…",
   "guestStatus": "Vous pouvez continuer à vous entraîner en tant qu’invité.",
   "answerSaving": "Enregistrement de la réponse…",
   "answerOnline": "Stockage local indisponible. Envoi de la réponse…",
   "confirmSignup": "Si l’inscription est possible, vous recevrez un e-mail de confirmation. Ouvrez le lien, puis connectez-vous ici.",
   "invalidLogin": "Adresse e-mail ou mot de passe incorrect.",
   "emailUnconfirmed": "Veuillez d’abord confirmer votre adresse e-mail en ouvrant le lien reçu.",
   "accountError": "Impossible de traiter le compte. Vérifiez vos informations et réessayez. Si la limite d’envoi d’e-mails est atteinte, réessayez plus tard.",
   "logoutError": "Déconnexion impossible. Veuillez réessayer.",
   "accountsUnconfigured": "Les comptes ne sont pas encore connectés. Vous pouvez essayer la version de test en tant qu’invité.",
   "accountConfigError": "Vérifiez la configuration : URL du projet et clé publique « Publishable Key » requises.",
   "accountWelcome": "Connectez-vous ou créez un compte de test.",
   "accountUnavailable": "Connexion au compte indisponible. Vous pouvez vous entraîner en tant qu’invité.",
   "noSavedErrors": "Aucune erreur enregistrée à revoir pour cette sélection.",
   "savedErrorsError": "Impossible de lancer la révision des erreurs enregistrées."
  },
  "es": {
   "title": "Entrenador de idiomas",
   "uiLanguage": "Idioma de la interfaz y de base",
   "language": "Idioma",
   "choose": "¿Qué idioma quieres practicar con {base}?",
   "menu": "¿Qué quieres practicar entre {de} y {language}?",
   "next": "Siguiente →",
   "languagesBack": "← Selección de idioma",
   "modesBack": "← Tipos de ejercicios",
   "words": "📚 Palabras",
   "wordsDesc": "Practicar vocabulario",
   "sentences": "💬 Frases",
   "sentencesDesc": "Practicar situaciones cotidianas",
   "grammar": "✏️ Gramática",
   "grammarDesc": "Comprender y practicar las formas",
   "topic": "Tema",
   "situation": "Situación",
   "direction": "Dirección",
   "start": "Empezar a practicar",
   "setupWords": "¿En qué dirección quieres practicar?",
   "setupSentences": "¿Qué frases quieres practicar?",
   "setupGrammar": "¿Qué tema de gramática quieres practicar?",
   "allSituations": "Todas las situaciones",
   "allTopics": "Todos los temas",
   "listen": "🔊 Escuchar: {language}",
   "stats": "{score} correctas de {answered}",
   "correct": "¡Correcto!",
   "solution": "Respuesta correcta: {answer}",
   "example": "Frase de ejemplo:",
   "finish": "Terminar · Ver errores",
   "reviewTitle": "Resultados de la sesión",
   "reviewStats": "{score} correctas de {answered} respuestas · {mistakes} ejercicios distintos con errores",
   "noMistakes": "No hubo errores en esta sesión.",
   "yourAnswer": "Tu respuesta:",
   "wrongCount": "{count}× incorrecta",
   "recovered": "correcta después",
   "repeat": "Repetir errores",
   "newRound": "Nueva sesión",
   "speechError": "Este navegador no admite la síntesis de voz.",
   "sentenceError": "No se pudieron cargar las frases. Revisa los archivos subidos.",
   "grammarError": "No se pudieron cargar los ejercicios de gramática. Revisa los archivos subidos.",
   "startError": "No se pudo iniciar el ejercicio. Revisa los archivos e inténtalo de nuevo.",
   "de": "Alemán",
   "en": "Inglés",
   "fr": "Francés",
   "es": "Español",
   "it": "Italiano",
   "pl": "Polaco",
   "testVersion": "🧪 Versión de prueba de cuentas",
   "oldTrainer": "Abrir el sitio de aprendizaje original",
   "guestLabel": "Invitado · Resultados solo de esta sesión",
   "signedIn": "Sesión iniciada: {name}",
   "learner": "Estudiante",
   "accountName": "Nombre (opcional)",
   "accountEmail": "Correo electrónico",
   "accountPassword": "Contraseña",
   "accountLogin": "Iniciar sesión",
   "accountSignup": "Crear cuenta",
   "accountLogout": "Cerrar sesión",
   "accountSync": "Sincronizar",
   "progressOpen": "Mi progreso guardado",
   "progressTitle": "Mi progreso",
   "savedErrors": "Repasar los errores guardados",
   "noPairAnswers": "Todavía no hay respuestas guardadas para {base} ↔ {target}. Empieza un ejercicio.",
   "progressWords": "Palabras",
   "progressSentences": "Frases",
   "progressGrammar": "Gramática",
   "progressStats": "{mode}: {correct} de {total} respuestas correctas · {tasks} ejercicios/direcciones practicados · {errors} errores pendientes",
   "syncPending": "{count} respuestas están pendientes de envío.",
   "syncDone": "Progreso sincronizado con la base de datos.",
   "syncOffline": "No se puede conectar. Las respuestas no enviadas quedan pendientes en este dispositivo. Usa «Sincronizar» más tarde.",
   "syncStorageError": "No se puede guardar ahora. Mantén la página abierta y vuelve a intentar «Sincronizar».",
   "progressLoading": "Cargando el progreso…",
   "guestStatus": "Puedes seguir practicando como invitado.",
   "answerSaving": "Guardando la respuesta…",
   "answerOnline": "El almacenamiento local no está disponible. Enviando la respuesta…",
   "confirmSignup": "Si el registro es posible, recibirás un correo de confirmación. Abre el enlace y luego inicia sesión aquí.",
   "invalidLogin": "Correo electrónico o contraseña incorrectos.",
   "emailUnconfirmed": "Confirma primero tu correo usando el enlace recibido.",
   "accountError": "No se pudo procesar la cuenta. Comprueba tus datos e inténtalo de nuevo. Si se alcanza el límite de correos, inténtalo más tarde.",
   "logoutError": "No se pudo cerrar la sesión. Inténtalo de nuevo.",
   "accountsUnconfigured": "Las cuentas aún no están conectadas. Puedes probar la versión de prueba como invitado.",
   "accountConfigError": "Revisa la configuración: se requieren la URL del proyecto y la clave pública «Publishable Key».",
   "accountWelcome": "Inicia sesión o crea una cuenta de prueba.",
   "accountUnavailable": "La conexión de cuentas no está disponible. Puedes practicar como invitado.",
   "noSavedErrors": "No hay errores guardados pendientes para esta selección.",
   "savedErrorsError": "No se pudo iniciar el repaso de errores guardados."
  },
  "it": {
   "title": "Allenamento linguistico",
   "uiLanguage": "Lingua dell’interfaccia e di base",
   "language": "Lingua",
   "choose": "Quale lingua vuoi esercitare insieme a {base}?",
   "menu": "Cosa vuoi esercitare tra {de} e {language}?",
   "next": "Avanti →",
   "languagesBack": "← Scelta della lingua",
   "modesBack": "← Tipi di esercizi",
   "words": "📚 Parole",
   "wordsDesc": "Esercitare il vocabolario",
   "sentences": "💬 Frasi",
   "sentencesDesc": "Esercitare situazioni quotidiane",
   "grammar": "✏️ Grammatica",
   "grammarDesc": "Capire ed esercitare le forme",
   "topic": "Argomento",
   "situation": "Situazione",
   "direction": "Direzione",
   "start": "Inizia a esercitarti",
   "setupWords": "In quale direzione vuoi esercitarti?",
   "setupSentences": "Quali frasi vuoi esercitare?",
   "setupGrammar": "Quale argomento di grammatica vuoi esercitare?",
   "allSituations": "Tutte le situazioni",
   "allTopics": "Tutti gli argomenti",
   "listen": "🔊 Ascolta: {language}",
   "stats": "{score} corrette su {answered}",
   "correct": "Corretto!",
   "solution": "Risposta corretta: {answer}",
   "example": "Frase di esempio:",
   "finish": "Termina · Vedi gli errori",
   "reviewTitle": "Risultati della sessione",
   "reviewStats": "{score} corrette su {answered} risposte · {mistakes} esercizi diversi con errori",
   "noMistakes": "Nessun errore in questa sessione.",
   "yourAnswer": "La tua risposta:",
   "wrongCount": "{count}× errata",
   "recovered": "corretta in seguito",
   "repeat": "Ripeti gli errori",
   "newRound": "Nuova sessione",
   "speechError": "Questo browser non supporta la sintesi vocale.",
   "sentenceError": "Impossibile caricare le frasi. Controlla i file caricati.",
   "grammarError": "Impossibile caricare gli esercizi di grammatica. Controlla i file caricati.",
   "startError": "Impossibile avviare l’esercizio. Controlla i file e riprova.",
   "de": "Tedesco",
   "en": "Inglese",
   "fr": "Francese",
   "es": "Spagnolo",
   "it": "Italiano",
   "pl": "Polacco",
   "testVersion": "🧪 Versione di prova degli account",
   "oldTrainer": "Apri il sito di apprendimento originale",
   "guestLabel": "Ospite · Risultati solo di questa sessione",
   "signedIn": "Accesso effettuato: {name}",
   "learner": "Studente",
   "accountName": "Nome (facoltativo)",
   "accountEmail": "Email",
   "accountPassword": "Password",
   "accountLogin": "Accedi",
   "accountSignup": "Crea un account",
   "accountLogout": "Esci",
   "accountSync": "Sincronizza",
   "progressOpen": "I miei progressi salvati",
   "progressTitle": "I miei progressi",
   "savedErrors": "Ripassa gli errori salvati",
   "noPairAnswers": "Non ci sono ancora risposte salvate per {base} ↔ {target}. Inizia un esercizio.",
   "progressWords": "Parole",
   "progressSentences": "Frasi",
   "progressGrammar": "Grammatica",
   "progressStats": "{mode}: {correct} risposte corrette su {total} · {tasks} esercizi/direzioni svolti · {errors} errori da ripassare",
   "syncPending": "{count} risposte sono in attesa di invio.",
   "syncDone": "Progressi sincronizzati con il database.",
   "syncOffline": "Connessione non disponibile. Le risposte non inviate restano in attesa su questo dispositivo. Usa «Sincronizza» più tardi.",
   "syncStorageError": "Al momento non è possibile salvare. Lascia la pagina aperta e riprova con «Sincronizza».",
   "progressLoading": "Caricamento dei progressi…",
   "guestStatus": "Puoi continuare a esercitarti come ospite.",
   "answerSaving": "Salvataggio della risposta…",
   "answerOnline": "Archivio locale non disponibile. Invio della risposta…",
   "confirmSignup": "Se la registrazione è possibile, riceverai un’email di conferma. Apri il link, poi accedi qui.",
   "invalidLogin": "Email o password errati.",
   "emailUnconfirmed": "Conferma prima la tua email tramite il link ricevuto.",
   "accountError": "Impossibile elaborare l’account. Controlla i dati e riprova. Se è stato raggiunto il limite delle email, riprova più tardi.",
   "logoutError": "Impossibile uscire. Riprova.",
   "accountsUnconfigured": "Gli account non sono ancora collegati. Puoi provare la versione di prova come ospite.",
   "accountConfigError": "Controlla la configurazione: servono l’URL del progetto e la chiave pubblica «Publishable Key».",
   "accountWelcome": "Accedi o crea un account di prova.",
   "accountUnavailable": "Connessione agli account non disponibile. Puoi esercitarti come ospite.",
   "noSavedErrors": "Non ci sono errori salvati da ripassare per questa selezione.",
   "savedErrorsError": "Impossibile avviare il ripasso degli errori salvati."
  },
  "pl": {
   "title": "Trener językowy",
   "uiLanguage": "Język interfejsu i język bazowy",
   "language": "Język",
   "choose": "Jaki język chcesz ćwiczyć w parze z językiem {base}?",
   "menu": "Co chcesz ćwiczyć w parze języków {de} i {language}?",
   "next": "Dalej →",
   "languagesBack": "← Wybór języka",
   "modesBack": "← Rodzaje ćwiczeń",
   "words": "📚 Słowa",
   "wordsDesc": "Ćwicz słownictwo",
   "sentences": "💬 Zdania",
   "sentencesDesc": "Ćwicz codzienne sytuacje",
   "grammar": "✏️ Gramatyka",
   "grammarDesc": "Poznaj i ćwicz formy gramatyczne",
   "topic": "Temat",
   "situation": "Sytuacja",
   "direction": "Kierunek",
   "start": "Rozpocznij ćwiczenie",
   "setupWords": "W którym kierunku chcesz ćwiczyć?",
   "setupSentences": "Jakie zdania chcesz ćwiczyć?",
   "setupGrammar": "Jaki temat gramatyczny chcesz ćwiczyć?",
   "allSituations": "Wszystkie sytuacje",
   "allTopics": "Wszystkie tematy",
   "listen": "🔊 Posłuchaj: {language}",
   "stats": "Poprawne: {score} z {answered}",
   "correct": "Dobrze!",
   "solution": "Poprawna odpowiedź: {answer}",
   "example": "Przykładowe zdanie:",
   "finish": "Zakończ rundę · Zobacz błędy",
   "reviewTitle": "Podsumowanie rundy",
   "reviewStats": "Poprawne: {score} z {answered} odpowiedzi · Różne zadania z błędem: {mistakes}",
   "noMistakes": "Brak błędów w tej rundzie.",
   "yourAnswer": "Twoja odpowiedź:",
   "wrongCount": "Błędnie: {count}×",
   "recovered": "później poprawnie",
   "repeat": "Powtórz błędne zadania",
   "newRound": "Nowa runda",
   "speechError": "Ta przeglądarka nie obsługuje syntezy mowy.",
   "sentenceError": "Nie udało się wczytać zdań. Sprawdź przesłane pliki.",
   "grammarError": "Nie udało się wczytać ćwiczeń gramatycznych. Sprawdź przesłane pliki.",
   "startError": "Nie udało się rozpocząć ćwiczenia. Sprawdź pliki i spróbuj ponownie.",
   "de": "Niemiecki",
   "en": "Angielski",
   "fr": "Francuski",
   "es": "Hiszpański",
   "it": "Włoski",
   "pl": "Polski",
   "testVersion": "🧪 Wersja testowa kont",
   "oldTrainer": "Otwórz dotychczasowy serwis do nauki",
   "guestLabel": "Gość · Wyniki tylko z tej sesji",
   "signedIn": "Zalogowano: {name}",
   "learner": "Uczący się",
   "accountName": "Imię (opcjonalnie)",
   "accountEmail": "Adres e-mail",
   "accountPassword": "Hasło",
   "accountLogin": "Zaloguj się",
   "accountSignup": "Utwórz konto",
   "accountLogout": "Wyloguj się",
   "accountSync": "Synchronizuj",
   "progressOpen": "Moje zapisane postępy",
   "progressTitle": "Moje postępy",
   "savedErrors": "Powtórz zapisane błędy",
   "noPairAnswers": "Nie ma jeszcze zapisanych odpowiedzi dla {base} ↔ {target}. Rozpocznij ćwiczenie.",
   "progressWords": "Słowa",
   "progressSentences": "Zdania",
   "progressGrammar": "Gramatyka",
   "progressStats": "{mode}: {correct} z {total} poprawnych odpowiedzi · {tasks} wykonanych zadań/kierunków · {errors} błędów do powtórzenia",
   "syncPending": "{count} odpowiedzi czeka na przesłanie.",
   "syncDone": "Postępy zsynchronizowane z bazą danych.",
   "syncOffline": "Nie można się połączyć. Nieprzesłane odpowiedzi pozostają zapisane na tym urządzeniu. Później użyj opcji „Synchronizuj”.",
   "syncStorageError": "Obecnie nie można zapisać. Nie zamykaj strony i ponownie wybierz „Synchronizuj”.",
   "progressLoading": "Wczytywanie postępów…",
   "guestStatus": "Możesz dalej ćwiczyć jako gość.",
   "answerSaving": "Zapisywanie odpowiedzi…",
   "answerOnline": "Pamięć lokalna jest niedostępna. Przesyłanie odpowiedzi…",
   "confirmSignup": "Jeśli rejestracja jest możliwa, otrzymasz e-mail z potwierdzeniem. Otwórz link, a następnie zaloguj się tutaj.",
   "invalidLogin": "Nieprawidłowy adres e-mail lub hasło.",
   "emailUnconfirmed": "Najpierw potwierdź adres e-mail za pomocą otrzymanego linku.",
   "accountError": "Nie udało się obsłużyć konta. Sprawdź dane i spróbuj ponownie. Jeśli osiągnięto limit wiadomości e-mail, spróbuj później.",
   "logoutError": "Nie udało się wylogować. Spróbuj ponownie.",
   "accountsUnconfigured": "Konta nie są jeszcze połączone. Możesz wypróbować wersję testową jako gość.",
   "accountConfigError": "Sprawdź konfigurację: wymagane są adres URL projektu i publiczny klucz „Publishable Key”.",
   "accountWelcome": "Zaloguj się lub utwórz konto testowe.",
   "accountUnavailable": "Połączenie z kontem jest niedostępne. Możesz ćwiczyć jako gość.",
   "noSavedErrors": "Brak zapisanych błędów do powtórzenia dla tego wyboru.",
   "savedErrorsError": "Nie udało się rozpocząć powtórki zapisanych błędów."
  }
 },
 "categories": {
  "de": {
   "Adjektivformen": "Adjektivformen",
   "Alltag": "Alltag",
   "Artikel & Präpositionen": "Artikel & Präpositionen",
   "Artikel und Pronomen": "Artikel und Pronomen",
   "Begrüßung": "Begrüßung",
   "Eigenschaften": "Eigenschaften",
   "Einkaufen": "Einkaufen",
   "Essen & Trinken": "Essen & Trinken",
   "Familie": "Familie",
   "Familie & Alltag": "Familie & Alltag",
   "Fragen": "Fragen",
   "Fälle": "Fälle",
   "Gesundheit": "Gesundheit",
   "Im Café": "Im Café",
   "Im Hotel": "Im Hotel",
   "Kleidung": "Kleidung",
   "Menschen": "Menschen",
   "Orte": "Orte",
   "Präpositionen und Wortformen": "Präpositionen und Wortformen",
   "Reisen": "Reisen",
   "Unterwegs": "Unterwegs",
   "Verbformen": "Verbformen",
   "Vergangenheit": "Vergangenheit",
   "Wohnen": "Wohnen",
   "Zahlen": "Zahlen",
   "Zeit": "Zeit",
   "Zeitformen": "Zeitformen"
  },
  "en": {
   "Adjektivformen": "Adjective forms",
   "Alltag": "Everyday life",
   "Artikel & Präpositionen": "Articles and prepositions",
   "Artikel und Pronomen": "Articles and pronouns",
   "Begrüßung": "Greetings",
   "Eigenschaften": "Qualities",
   "Einkaufen": "Shopping",
   "Essen & Trinken": "Food and drink",
   "Familie": "Family",
   "Familie & Alltag": "Family and everyday life",
   "Fragen": "Questions",
   "Fälle": "Cases",
   "Gesundheit": "Health",
   "Im Café": "At the café",
   "Im Hotel": "At the hotel",
   "Kleidung": "Clothing",
   "Menschen": "People",
   "Orte": "Places",
   "Präpositionen und Wortformen": "Prepositions and word forms",
   "Reisen": "Travel",
   "Unterwegs": "Getting around",
   "Verbformen": "Verb forms",
   "Vergangenheit": "Past tense",
   "Wohnen": "Home",
   "Zahlen": "Numbers",
   "Zeit": "Time",
   "Zeitformen": "Tenses"
  },
  "fr": {
   "Adjektivformen": "Formes des adjectifs",
   "Alltag": "Vie quotidienne",
   "Artikel & Präpositionen": "Articles et prépositions",
   "Artikel und Pronomen": "Articles et pronoms",
   "Begrüßung": "Salutations",
   "Eigenschaften": "Qualités",
   "Einkaufen": "Achats",
   "Essen & Trinken": "Nourriture et boissons",
   "Familie": "Famille",
   "Familie & Alltag": "Famille et quotidien",
   "Fragen": "Questions",
   "Fälle": "Cas grammaticaux",
   "Gesundheit": "Santé",
   "Im Café": "Au café",
   "Im Hotel": "À l’hôtel",
   "Kleidung": "Vêtements",
   "Menschen": "Personnes",
   "Orte": "Lieux",
   "Präpositionen und Wortformen": "Prépositions et formes des mots",
   "Reisen": "Voyages",
   "Unterwegs": "En déplacement",
   "Verbformen": "Formes verbales",
   "Vergangenheit": "Passé",
   "Wohnen": "Logement",
   "Zahlen": "Nombres",
   "Zeit": "Temps",
   "Zeitformen": "Temps verbaux"
  },
  "es": {
   "Adjektivformen": "Formas de adjetivos",
   "Alltag": "Vida cotidiana",
   "Artikel & Präpositionen": "Artículos y preposiciones",
   "Artikel und Pronomen": "Artículos y pronombres",
   "Begrüßung": "Saludos",
   "Eigenschaften": "Cualidades",
   "Einkaufen": "Compras",
   "Essen & Trinken": "Comida y bebida",
   "Familie": "Familia",
   "Familie & Alltag": "Familia y vida cotidiana",
   "Fragen": "Preguntas",
   "Fälle": "Casos gramaticales",
   "Gesundheit": "Salud",
   "Im Café": "En la cafetería",
   "Im Hotel": "En el hotel",
   "Kleidung": "Ropa",
   "Menschen": "Personas",
   "Orte": "Lugares",
   "Präpositionen und Wortformen": "Preposiciones y formas de palabras",
   "Reisen": "Viajes",
   "Unterwegs": "Desplazamientos",
   "Verbformen": "Formas verbales",
   "Vergangenheit": "Pasado",
   "Wohnen": "Vivienda",
   "Zahlen": "Números",
   "Zeit": "Tiempo",
   "Zeitformen": "Tiempos verbales"
  },
  "it": {
   "Adjektivformen": "Forme degli aggettivi",
   "Alltag": "Vita quotidiana",
   "Artikel & Präpositionen": "Articoli e preposizioni",
   "Artikel und Pronomen": "Articoli e pronomi",
   "Begrüßung": "Saluti",
   "Eigenschaften": "Qualità",
   "Einkaufen": "Acquisti",
   "Essen & Trinken": "Cibo e bevande",
   "Familie": "Famiglia",
   "Familie & Alltag": "Famiglia e vita quotidiana",
   "Fragen": "Domande",
   "Fälle": "Casi grammaticali",
   "Gesundheit": "Salute",
   "Im Café": "Al bar",
   "Im Hotel": "In hotel",
   "Kleidung": "Abbigliamento",
   "Menschen": "Persone",
   "Orte": "Luoghi",
   "Präpositionen und Wortformen": "Preposizioni e forme delle parole",
   "Reisen": "Viaggi",
   "Unterwegs": "In viaggio",
   "Verbformen": "Forme verbali",
   "Vergangenheit": "Passato",
   "Wohnen": "Abitare",
   "Zahlen": "Numeri",
   "Zeit": "Tempo",
   "Zeitformen": "Tempi verbali"
  },
  "pl": {
   "Adjektivformen": "Formy przymiotników",
   "Alltag": "Życie codzienne",
   "Artikel & Präpositionen": "Rodzajniki i przyimki",
   "Artikel und Pronomen": "Rodzajniki i zaimki",
   "Begrüßung": "Powitania",
   "Eigenschaften": "Cechy",
   "Einkaufen": "Zakupy",
   "Essen & Trinken": "Jedzenie i picie",
   "Familie": "Rodzina",
   "Familie & Alltag": "Rodzina i życie codzienne",
   "Fragen": "Pytania",
   "Fälle": "Przypadki",
   "Gesundheit": "Zdrowie",
   "Im Café": "W kawiarni",
   "Im Hotel": "W hotelu",
   "Kleidung": "Ubrania",
   "Menschen": "Ludzie",
   "Orte": "Miejsca",
   "Präpositionen und Wortformen": "Przyimki i formy wyrazów",
   "Reisen": "Podróże",
   "Unterwegs": "W drodze",
   "Verbformen": "Formy czasowników",
   "Vergangenheit": "Czas przeszły",
   "Wohnen": "Mieszkanie",
   "Zahlen": "Liczby",
   "Zeit": "Czas",
   "Zeitformen": "Czasy gramatyczne"
  }
 }
};
let uiLanguage='de';
try{const saved=localStorage.getItem('trainer-ui-language');if(window.TRAINER_I18N.texts[saved])uiLanguage=saved}catch(e){}
function t(key,params={}){let value=window.TRAINER_I18N.texts[uiLanguage][key]??window.TRAINER_I18N.texts.de[key]??key;return value.replace(/\{(\w+)\}/g,(_,name)=>params[name]??'{'+name+'}')}
function categoryName(category){return window.TRAINER_I18N.categories[uiLanguage][category]??category}
function languageName(id){return t(id)}

for(const [locale,values] of Object.entries({"de": ["🗣️ Dialoge", "Unterhaltungen mit Antwortauswahl", "Welche Unterhaltung möchtest du üben?", "Die Dialoge konnten nicht geladen werden.", "Dialoge", "Gesprächspartner", "Du", "Schritt {step} von {total}", "Antwortsprache", "Wähle die passende Antwort."], "en": ["🗣️ Dialogues", "Conversations with a choice of replies", "Which conversation would you like to practise?", "The dialogues could not be loaded.", "Dialogues", "Conversation partner", "You", "Step {step} of {total}", "Reply language", "Choose the appropriate reply."], "fr": ["🗣️ Dialogues", "Conversations avec choix de réponses", "Quelle conversation souhaitez-vous pratiquer ?", "Impossible de charger les dialogues.", "Dialogues", "Interlocuteur", "Vous", "Étape {step} sur {total}", "Langue des réponses", "Choisissez la réponse adaptée."], "es": ["🗣️ Diálogos", "Conversaciones con respuestas a elegir", "¿Qué conversación quieres practicar?", "No se pudieron cargar los diálogos.", "Diálogos", "Interlocutor", "Tú", "Paso {step} de {total}", "Idioma de las respuestas", "Elige la respuesta adecuada."], "it": ["🗣️ Dialoghi", "Conversazioni con risposte a scelta", "Quale conversazione vuoi praticare?", "Impossibile caricare i dialoghi.", "Dialoghi", "Interlocutore", "Tu", "Passaggio {step} di {total}", "Lingua delle risposte", "Scegli la risposta adatta."], "pl": ["🗣️ Dialogi", "Rozmowy z wyborem odpowiedzi", "Jaką rozmowę chcesz przećwiczyć?", "Nie udało się wczytać dialogów.", "Dialogi", "Rozmówca", "Ty", "Krok {step} z {total}", "Język odpowiedzi", "Wybierz odpowiednią odpowiedź."]}))Object.assign(window.TRAINER_I18N.texts[locale],Object.fromEntries(["dialogues", "dialoguesDesc", "setupDialogues", "dialogueError", "progressDialogues", "dialoguePartner", "dialogueYou", "dialogueStep", "replyLanguage", "dialogueInstruction"].map((key,i)=>[key,values[i]])));

for(const [locale,text] of Object.entries({"de": "Du möchtest sagen: {reply}", "en": "You want to say: {reply}", "fr": "Vous voulez dire : {reply}", "es": "Quieres decir: {reply}", "it": "Vuoi dire: {reply}", "pl": "Chcesz powiedzieć: {reply}"}))window.TRAINER_I18N.texts[locale].dialogueIntent=text;

// Compact progress cards keep category and unresolved count separate from totals.
for (const [locale, values] of Object.entries({
 de: ['offene Fehler', '{correct} von {total} Antworten richtig · {tasks} Aufgaben/Richtungen bearbeitet'],
 en: ['unresolved mistakes', '{correct} of {total} answers correct · {tasks} tasks/directions practiced'],
 fr: ['erreurs à revoir', '{correct} réponses correctes sur {total} · {tasks} exercices/sens pratiqués'],
 es: ['errores pendientes', '{correct} de {total} respuestas correctas · {tasks} ejercicios/direcciones practicados'],
 it: ['errori da ripassare', '{correct} risposte corrette su {total} · {tasks} esercizi/direzioni svolti'],
 pl: ['błędów do powtórzenia', '{correct} z {total} poprawnych odpowiedzi · {tasks} wykonanych zadań/kierunków']
})) Object.assign(window.TRAINER_I18N.texts[locale], {progressOpenErrors: values[0], progressDetails: values[1]});
