window.VOCAB=window.VOCAB||{};
window.VOCAB.pl=[
['Hallo','cześć','Begrüßung'],['Guten Morgen','dzień dobry','Begrüßung'],['Auf Wiedersehen','do widzenia','Begrüßung'],['Danke','dziękuję','Begrüßung'],['Bitte','proszę','Begrüßung'],['Ja','tak','Alltag'],['Nein','nie','Alltag'],['Entschuldigung','przepraszam','Alltag'],['Ich','ja','Alltag'],['Du','ty','Alltag'],['Wir','my','Alltag'],['Heute','dzisiaj','Zeit'],['Morgen (der nächste Tag)','jutro','Zeit'],['Gestern','wczoraj','Zeit'],['Jetzt','teraz','Zeit'],['Haus','dom','Wohnen'],['Wohnung','mieszkanie','Wohnen'],['Zimmer','pokój','Wohnen'],['Tür','drzwi','Wohnen'],['Fenster','okno','Wohnen'],['Tisch','stół','Wohnen'],['Stuhl','krzesło','Wohnen'],['Familie','rodzina','Familie'],['Mutter','matka','Familie'],['Vater','ojciec','Familie'],['Kind','dziecko','Familie'],['Tochter','córka','Familie'],['Sohn','syn','Familie'],['Freund','przyjaciel','Menschen'],['Frau','kobieta','Menschen'],['Mann','mężczyzna','Menschen'],['Wasser','woda','Essen & Trinken'],['Brot','chleb','Essen & Trinken'],['Milch','mleko','Essen & Trinken'],['Kaffee','kawa','Essen & Trinken'],['Tee','herbata','Essen & Trinken'],['Apfel','jabłko','Essen & Trinken'],['Suppe','zupa','Essen & Trinken'],['Frühstück','śniadanie','Essen & Trinken'],['Essen (Substantiv)','jedzenie','Essen & Trinken'],['Auto','samochód','Reisen'],['Zug','pociąg','Reisen'],['Bahnhof','dworzec','Reisen'],['Flughafen','lotnisko','Reisen'],['Straße','ulica','Reisen'],['Stadt','miasto','Reisen'],['links','w lewo','Reisen'],['rechts','w prawo','Reisen'],['Wo?','gdzie?','Fragen'],['Wie viel?','ile?','Fragen'],
['Guten Abend','dobry wieczór','Begrüßung'],['Gute Nacht','dobranoc','Begrüßung'],['Bis später','do zobaczenia','Begrüßung'],
['Er','on','Alltag'],['Sie (Einzahl)','ona','Alltag'],['Ihr','wy','Alltag'],['Sie (Mehrzahl)','oni','Alltag'],
['gut','dobry','Eigenschaften'],['schlecht','zły','Eigenschaften'],['groß','duży','Eigenschaften'],['klein','mały','Eigenschaften'],['neu','nowy','Eigenschaften'],['alt (Gegenstand)','stary','Eigenschaften'],['schön','piękny','Eigenschaften'],['schnell','szybki','Eigenschaften'],['langsam','wolny','Eigenschaften'],['warm','ciepły','Eigenschaften'],['kalt','zimny','Eigenschaften'],['rot','czerwony','Eigenschaften'],
['Montag','poniedziałek','Zeit'],['Dienstag','wtorek','Zeit'],['Mittwoch','środa','Zeit'],['Donnerstag','czwartek','Zeit'],['Freitag','piątek','Zeit'],['Samstag','sobota','Zeit'],['Sonntag','niedziela','Zeit'],['Tag','dzień','Zeit'],['Woche','tydzień','Zeit'],['Monat','miesiąc','Zeit'],['Jahr','rok','Zeit'],['Stunde','godzina','Zeit'],['Minute','minuta','Zeit'],
['Bruder','brat','Familie'],['Schwester','siostra','Familie'],['Großmutter','babcia','Familie'],['Großvater','dziadek','Familie'],['Ehemann','mąż','Familie'],['Ehefrau','żona','Familie'],['Nachbar','sąsiad','Menschen'],['Lehrer','nauczyciel','Menschen'],['Arzt','lekarz','Menschen'],
['Bett','łóżko','Wohnen'],['Küche','kuchnia','Wohnen'],['Badezimmer','łazienka','Wohnen'],['Schlüssel','klucz','Wohnen'],['Lampe','lampa','Wohnen'],['Garten','ogród','Wohnen'],['Buch','książka','Alltag'],['Handy','telefon komórkowy','Alltag'],['Geld','pieniądze','Alltag'],['Zeit (allgemein)','czas','Zeit'],
['Käse','ser','Essen & Trinken'],['Ei','jajko','Essen & Trinken'],['Fleisch','mięso','Essen & Trinken'],['Fisch','ryba','Essen & Trinken'],['Kartoffel','ziemniak','Essen & Trinken'],['Reis','ryż','Essen & Trinken'],['Banane','banan','Essen & Trinken'],['Orange (Frucht)','pomarańcza','Essen & Trinken'],['Zucker','cukier','Essen & Trinken'],['Salz','sól','Essen & Trinken'],['Mittagessen','obiad','Essen & Trinken'],['Abendessen','kolacja','Essen & Trinken'],['Bier','piwo','Essen & Trinken'],['Saft','sok','Essen & Trinken'],
['Laden','sklep','Einkaufen'],['Preis','cena','Einkaufen'],['Kasse (im Laden)','kasa','Einkaufen'],['Rechnung (im Restaurant)','rachunek','Einkaufen'],['Supermarkt','supermarket','Einkaufen'],
['Ticket','bilet','Reisen'],['Bus','autobus','Reisen'],['Fahrrad','rower','Reisen'],['Flugzeug','samolot','Reisen'],['Haltestelle','przystanek','Reisen'],['Dorf','wieś','Reisen'],['Land (Staat)','kraj','Reisen'],['Meer','morze','Reisen'],['Strand','plaża','Reisen'],['Hotel','hotel','Reisen'],
['hier','tutaj','Orte'],['dort','tam','Orte'],['oben','na górze','Orte'],['unten','na dole','Orte'],
['Wer?','kto?','Fragen'],['Was?','co?','Fragen'],['Wann?','kiedy?','Fragen'],['Warum?','dlaczego?','Fragen'],['Wie?','jak?','Fragen'],['Welcher?','który?','Fragen'],
['eins','jeden','Zahlen'],['zwei','dwa','Zahlen'],['drei','trzy','Zahlen'],['vier','cztery','Zahlen'],['fünf','pięć','Zahlen'],['sechs','sześć','Zahlen'],['sieben','siedem','Zahlen'],['acht','osiem','Zahlen'],['neun','dziewięć','Zahlen'],['zehn','dziesięć','Zahlen'],
["Gruß", "pozdrowienie", "Alltag"],
["Abschied", "pożegnanie", "Alltag"],
["Höflichkeit", "uprzejmość", "Alltag"],
["Lächeln", "uśmiech", "Alltag"],
["Gespräch", "rozmowa", "Alltag"],
["Niemand", "nikt", "Alltag"],
["Jemand", "ktoś", "Alltag"],
["alle", "wszyscy", "Alltag"],
["immer", "zawsze", "Alltag"],
["nie", "nigdy", "Alltag"],
["manchmal", "czasami", "Alltag"],
["oft", "często", "Alltag"],
["selten", "rzadko", "Alltag"],
["zusammen", "razem", "Alltag"],
["allein", "sam", "Alltag"],
["auch", "też", "Alltag"],
["nur", "tylko", "Alltag"],
["vielleicht", "może", "Alltag"],
["sicher (gewiss)", "na pewno", "Alltag"],
["hilfe!", "pomocy!", "Alltag"],
["Hilfe (Substantiv)", "pomoc", "Alltag"],
["Problem", "problem", "Alltag"],
["Frage", "pytanie", "Alltag"],
["Antwort", "odpowiedź", "Alltag"],
["Name", "imię", "Alltag"],
["Morgen (Tageszeit)", "poranek", "Zeit"],
["Abend", "wieczór", "Zeit"],
["Nacht", "noc", "Zeit"],
["Mittag (Tageszeit)", "południe", "Zeit"],
["Sekunde", "sekunda", "Zeit"],
["Frühling", "wiosna", "Zeit"],
["Sommer", "lato", "Zeit"],
["Herbst", "jesień", "Zeit"],
["Winter", "zima", "Zeit"],
["Wochenende", "weekend", "Zeit"],
["Ferien", "wakacje", "Zeit"],
["Geburtstag", "urodziny", "Zeit"],
["jung", "młody", "Eigenschaften"],
["glücklich", "szczęśliwy", "Eigenschaften"],
["traurig", "smutny", "Eigenschaften"],
["müde", "zmęczony", "Eigenschaften"],
["krank", "chory", "Eigenschaften"],
["gesund", "zdrowy", "Eigenschaften"],
["schwer (Gewicht)", "ciężki", "Eigenschaften"],
["leicht (Gewicht)", "lekki", "Eigenschaften"],
["teuer", "drogi", "Eigenschaften"],
["billig", "tani", "Eigenschaften"],
["voll", "pełny", "Eigenschaften"],
["leer", "pusty", "Eigenschaften"],
["kurz", "krótki", "Eigenschaften"],
["lang", "długi", "Eigenschaften"],
["wichtig", "ważny", "Eigenschaften"],
["fertig", "gotowy", "Eigenschaften"],
["Eltern", "rodzice", "Familie"],
["Geschwister", "rodzeństwo", "Familie"],
["Enkel (Junge)", "wnuk", "Familie"],
["Enkelin", "wnuczka", "Familie"],
["Tante", "ciocia", "Familie"],
["Onkel", "wujek", "Familie"],
["Cousin", "kuzyn", "Familie"],
["Cousine", "kuzynka", "Familie"],
["Freundin", "przyjaciółka", "Menschen"],
["Lehrerin", "nauczycielka", "Menschen"],
["Ärztin", "lekarka", "Menschen"],
["Gast", "gość", "Menschen"],
["Kollege", "kolega", "Menschen"],
["Kollegin", "koleżanka", "Menschen"],
["Dach", "dach", "Wohnen"],
["Wand", "ściana", "Wohnen"],
["Boden (Fußboden)", "podłoga", "Wohnen"],
["Treppe", "schody", "Wohnen"],
["Keller", "piwnica", "Wohnen"],
["Balkon", "balkon", "Wohnen"],
["Sofa", "kanapa", "Wohnen"],
["Schrank", "szafa", "Wohnen"],
["Regal", "półka", "Wohnen"],
["Spiegel", "lustro", "Wohnen"],
["Kühlschrank", "lodówka", "Wohnen"],
["Backofen", "piekarnik", "Wohnen"],
["Dusche", "prysznic", "Wohnen"],
["Toilette", "toaleta", "Wohnen"],
["Handtuch", "ręcznik", "Wohnen"],
["Butter", "masło", "Essen & Trinken"],
["Brötchen", "bułka", "Essen & Trinken"],
["Mehl", "mąka", "Essen & Trinken"],
["Öl (Speiseöl)", "olej", "Essen & Trinken"],
["Pfeffer", "pieprz", "Essen & Trinken"],
["Honig", "miód", "Essen & Trinken"],
["Marmelade", "dżem", "Essen & Trinken"],
["Joghurt", "jogurt", "Essen & Trinken"],
["Schokolade", "czekolada", "Essen & Trinken"],
["Kuchen", "ciasto", "Essen & Trinken"],
["Birne", "gruszka", "Essen & Trinken"],
["Erdbeere", "truskawka", "Essen & Trinken"],
["Tomate", "pomidor", "Essen & Trinken"],
["Gurke", "ogórek", "Essen & Trinken"],
["Zwiebel", "cebula", "Essen & Trinken"],
["Knoblauch", "czosnek", "Essen & Trinken"],
["Karotte", "marchewka", "Essen & Trinken"],
["Salat (Gemüse)", "sałata", "Essen & Trinken"],
["Hähnchen", "kurczak", "Essen & Trinken"],
["Wurst", "kiełbasa", "Essen & Trinken"],
["Schwein", "świnia", "Essen & Trinken"],
["Kuh", "krowa", "Essen & Trinken"],
["Pilz", "grzyb", "Essen & Trinken"],
["Bohne", "fasola", "Essen & Trinken"],
["Erbse", "groszek", "Essen & Trinken"],
["Nudeln", "makaron", "Essen & Trinken"],
["Spinat", "szpinak", "Essen & Trinken"],
["Mineralwasser", "woda mineralna", "Essen & Trinken"],
["Wein", "wino", "Essen & Trinken"],
["Getränk", "napój", "Essen & Trinken"],
["Kunde", "klient", "Einkaufen"],
["Kundin", "klientka", "Einkaufen"],
["Verkäufer", "sprzedawca", "Einkaufen"],
["Verkäuferin", "sprzedawczyni", "Einkaufen"],
["Karte (Zahlung)", "karta", "Einkaufen"],
["Bargeld", "gotówka", "Einkaufen"],
["Wechselgeld", "reszta", "Einkaufen"],
["Quittung", "paragon", "Einkaufen"],
["Angebot", "oferta", "Einkaufen"],
["Größe (Kleidung)", "rozmiar", "Einkaufen"],
["Reise", "podróż", "Reisen"],
["Urlaub", "urlop", "Reisen"],
["Koffer", "walizka", "Reisen"],
["Tasche", "torba", "Reisen"],
["Pass (Dokument)", "paszport", "Reisen"],
["Fahrplan", "rozkład jazdy", "Reisen"],
["Straßenbahn", "tramwaj", "Reisen"],
["Taxi", "taksówka", "Reisen"],
["Parkplatz", "parking", "Reisen"],
["Brücke", "most", "Reisen"],
["Fluss", "rzeka", "Reisen"],
["Berg", "góra", "Reisen"],
["Wald", "las", "Reisen"],
["See (Gewässer)", "jezioro", "Reisen"],
["Wetter", "pogoda", "Reisen"],
["Regen", "deszcz", "Reisen"],
["Schnee", "śnieg", "Reisen"],
["Sonne", "słońce", "Reisen"],
["Wind", "wiatr", "Reisen"],
["Wolke", "chmura", "Reisen"],
["Hose", "spodnie", "Kleidung"],
["Hemd", "koszula", "Kleidung"],
["Jacke", "kurtka", "Kleidung"],
["Mantel", "płaszcz", "Kleidung"],
["Schuh", "but", "Kleidung"],
["Socke", "skarpetka", "Kleidung"],
["Mütze", "czapka", "Kleidung"],
["Handschuh", "rękawiczka", "Kleidung"]
].map(([de,target,category])=>({de,target,category}));
