window.SENTENCES=window.SENTENCES||{};
window.SENTENCES.pl=[
// Einkaufen
['Ich möchte Brot kaufen.','Chcę kupić chleb.','Einkaufen'],
['Wie viel kostet das?','Ile to kosztuje?','Einkaufen'],
['Haben Sie Milch?','Czy mają państwo mleko?','Einkaufen'],
['Ich suche Äpfel.','Szukam jabłek.','Einkaufen'],
['Ich nehme zwei Stück.','Wezmę dwie sztuki.','Einkaufen'],
['Kann ich mit Karte bezahlen?','Czy mogę zapłacić kartą?','Einkaufen'],
['Ich bezahle bar.','Zapłacę gotówką.','Einkaufen'],
['Ich brauche eine Tüte.','Potrzebuję torby.','Einkaufen'],
['Wo ist die Kasse?','Gdzie jest kasa?','Einkaufen'],
['Das ist zu teuer.','To jest za drogie.','Einkaufen'],
// Im Café
['Einen Tisch für zwei Personen, bitte.','Poproszę stolik dla dwóch osób.','Im Café'],
['Ich hätte gern einen Kaffee.','Poproszę kawę.','Im Café'],
['Haben Sie Tee?','Czy mają państwo herbatę?','Im Café'],
['Ich möchte ein Glas Wasser.','Poproszę szklankę wody.','Im Café'],
['Haben Sie Kuchen?','Czy mają państwo ciasto?','Im Café'],
['Was empfehlen Sie?','Co państwo polecają?','Im Café'],
['Das schmeckt sehr gut.','To jest bardzo smaczne.','Im Café'],
['Die Rechnung, bitte.','Poproszę rachunek.','Im Café'],
['Kann ich hier sitzen?','Czy mogę tu usiąść?','Im Café'],
['Vielen Dank für Ihre Hilfe.','Dziękuję za pomoc.','Im Café'],
// Unterwegs
['Wo ist der Bahnhof?','Gdzie jest dworzec?','Unterwegs'],
['Ich suche die Bushaltestelle.','Szukam przystanku autobusowego.','Unterwegs'],
['Fährt dieser Bus ins Zentrum?','Czy ten autobus jedzie do centrum?','Unterwegs'],
['Ich brauche ein Ticket.','Potrzebuję biletu.','Unterwegs'],
['Wann fährt der Zug?','Kiedy odjeżdża pociąg?','Unterwegs'],
['Gehen Sie geradeaus.','Proszę iść prosto.','Unterwegs'],
['Biegen Sie links ab.','Proszę skręcić w lewo.','Unterwegs'],
['Biegen Sie rechts ab.','Proszę skręcić w prawo.','Unterwegs'],
['Ich weiß nicht, wo ich bin.','Nie wiem, gdzie jestem.','Unterwegs'],
['Ist es weit von hier?','Czy to daleko stąd?','Unterwegs'],
["Wo finde ich den Reis?", "Gdzie znajdę ryż?", "Einkaufen"],
["Ist das im Angebot?", "Czy to jest w promocji?", "Einkaufen"],
["Kann ich das anprobieren?", "Czy mogę to przymierzyć?", "Einkaufen"],
["Haben Sie das in einer anderen Größe?", "Czy mają państwo to w innym rozmiarze?", "Einkaufen"],
["Ich brauche einen Kassenbon.", "Potrzebuję paragonu.", "Einkaufen"],
["Gibt es frisches Brot?", "Czy jest świeży chleb?", "Einkaufen"],
["Ich schaue mich nur um.", "Tylko się rozglądam.", "Einkaufen"],
["Wo sind die Getränke?", "Gdzie są napoje?", "Einkaufen"],
["Kann ich das zurückgeben?", "Czy mogę to zwrócić?", "Einkaufen"],
["Ist der Laden noch geöffnet?", "Czy sklep jest jeszcze otwarty?", "Einkaufen"],
["Haben Sie eine Speisekarte?", "Czy mają państwo menu?", "Im Café"],
["Ich hätte gern einen Tee mit Zitrone.", "Poproszę herbatę z cytryną.", "Im Café"],
["Ohne Zucker, bitte.", "Bez cukru, proszę.", "Im Café"],
["Ist dieser Platz frei?", "Czy to miejsce jest wolne?", "Im Café"],
["Wir möchten bestellen.", "Chcemy zamówić.", "Im Café"],
["Gibt es etwas Vegetarisches?", "Czy jest coś wegetariańskiego?", "Im Café"],
["Kann ich noch etwas Wasser bekommen?", "Czy mogę dostać jeszcze trochę wody?", "Im Café"],
["Das Essen ist köstlich.", "Jedzenie jest pyszne.", "Im Café"],
["Wir möchten getrennt bezahlen.", "Chcemy zapłacić osobno.", "Im Café"],
["Wo ist die Toilette?", "Gdzie jest toaleta?", "Im Café"],
["Wie komme ich zum Flughafen?", "Jak dojadę na lotnisko?", "Unterwegs"],
["Wo kann ich ein Ticket kaufen?", "Gdzie mogę kupić bilet?", "Unterwegs"],
["An welcher Haltestelle muss ich aussteigen?", "Na którym przystanku mam wysiąść?", "Unterwegs"],
["Fährt der Zug pünktlich ab?", "Czy pociąg odjeżdża punktualnie?", "Unterwegs"],
["Ist dieser Platz besetzt?", "Czy to miejsce jest zajęte?", "Unterwegs"],
["Ich fahre nach Warschau.", "Jadę do Warszawy.", "Unterwegs"],
["Wie lange dauert die Fahrt?", "Jak długo trwa podróż?", "Unterwegs"],
["Der Bus kommt in zehn Minuten.", "Autobus przyjedzie za dziesięć minut.", "Unterwegs"],
["Ich suche diese Adresse.", "Szukam tego adresu.", "Unterwegs"],
["Können Sie mir den Weg zeigen?", "Czy mogą mi państwo pokazać drogę?", "Unterwegs"],
["Ich habe eine Reservierung.", "Mam rezerwację.", "Im Hotel"],
["Ist ein Zimmer frei?", "Czy jest wolny pokój?", "Im Hotel"],
["Für wie viele Nächte?", "Na ile nocy?", "Im Hotel"],
["Ich bleibe drei Nächte.", "Zostaję na trzy noce.", "Im Hotel"],
["Wann ist der Check-in?", "O której godzinie można się zameldować?", "Im Hotel"],
["Wann muss ich auschecken?", "O której godzinie muszę się wymeldować?", "Im Hotel"],
["Ist Frühstück im Preis enthalten?", "Czy śniadanie jest wliczone w cenę?", "Im Hotel"],
["Wie lautet das WLAN-Passwort?", "Jakie jest hasło do Wi-Fi?", "Im Hotel"],
["Mein Schlüssel funktioniert nicht.", "Mój klucz nie działa.", "Im Hotel"],
["Das Zimmer ist zu kalt.", "W pokoju jest za zimno.", "Im Hotel"],
["Haben Sie ein ruhigeres Zimmer?", "Czy mają państwo cichszy pokój?", "Im Hotel"],
["Wo ist der Aufzug?", "Gdzie jest winda?", "Im Hotel"],
["Gibt es einen Parkplatz?", "Czy jest parking?", "Im Hotel"],
["Können Sie ein Taxi rufen?", "Czy mogą państwo zamówić taksówkę?", "Im Hotel"],
["Ich brauche ein weiteres Handtuch.", "Potrzebuję jeszcze jednego ręcznika.", "Im Hotel"],
["Wo kann ich mein Gepäck lassen?", "Gdzie mogę zostawić bagaż?", "Im Hotel"],
["Ich habe meinen Pass dabei.", "Mam przy sobie paszport.", "Im Hotel"],
["Gibt es hier eine Klimaanlage?", "Czy jest tu klimatyzacja?", "Im Hotel"],
["Ich möchte das Zimmer wechseln.", "Chcę zmienić pokój.", "Im Hotel"],
["Ich komme morgen wieder.", "Wrócę jutro.", "Im Hotel"],
["Wie heißt du?", "Jak masz na imię?", "Familie & Alltag"],
["Ich heiße Anna.", "Mam na imię Anna.", "Familie & Alltag"],
["Wo wohnst du?", "Gdzie mieszkasz?", "Familie & Alltag"],
["Ich wohne in Bremen.", "Mieszkam w Bremie.", "Familie & Alltag"],
["Hast du Geschwister?", "Masz rodzeństwo?", "Familie & Alltag"],
["Meine Kinder sind zu Hause.", "Moje dzieci są w domu.", "Familie & Alltag"],
["Wir essen zusammen.", "Jemy razem.", "Familie & Alltag"],
["Das ist meine Schwester.", "To jest moja siostra.", "Familie & Alltag"],
["Ich rufe meine Mutter an.", "Dzwonię do mamy.", "Familie & Alltag"],
["Wann kommst du zurück?", "Kiedy wrócisz?", "Familie & Alltag"],
["Ich bin gleich da.", "Zaraz będę.", "Familie & Alltag"],
["Mach bitte das Fenster zu.", "Zamknij proszę okno.", "Familie & Alltag"],
["Ich muss heute arbeiten.", "Muszę dziś pracować.", "Familie & Alltag"],
["Wir gehen spazieren.", "Idziemy na spacer.", "Familie & Alltag"],
["Wo sind meine Schlüssel?", "Gdzie są moje klucze?", "Familie & Alltag"],
["Ich brauche eine Pause.", "Potrzebuję przerwy.", "Familie & Alltag"],
["Das Kind schläft.", "Dziecko śpi.", "Familie & Alltag"],
["Wir sehen uns morgen.", "Widzimy się jutro.", "Familie & Alltag"],
["Hast du heute Zeit?", "Masz dziś czas?", "Familie & Alltag"],
["Ich helfe dir gern.", "Chętnie ci pomogę.", "Familie & Alltag"],
["Ich brauche einen Arzt.", "Potrzebuję lekarza.", "Gesundheit"],
["Mir ist schlecht.", "Jest mi niedobrze.", "Gesundheit"],
["Ich habe Kopfschmerzen.", "Boli mnie głowa.", "Gesundheit"],
["Mein Bauch tut weh.", "Boli mnie brzuch.", "Gesundheit"],
["Ich habe Fieber.", "Mam gorączkę.", "Gesundheit"],
["Wo ist die Apotheke?", "Gdzie jest apteka?", "Gesundheit"],
["Ich habe einen Termin.", "Mam umówioną wizytę.", "Gesundheit"],
["Wann ist die Praxis geöffnet?", "Kiedy przychodnia jest otwarta?", "Gesundheit"],
["Ich nehme Medikamente.", "Biorę leki.", "Gesundheit"],
["Ich habe eine Allergie.", "Mam alergię.", "Gesundheit"],
["Ich brauche Hilfe.", "Potrzebuję pomocy.", "Gesundheit"],
["Mir geht es besser.", "Czuję się lepiej.", "Gesundheit"],
["Ich möchte einen Termin vereinbaren.", "Chcę umówić wizytę.", "Gesundheit"],
["Ich habe Husten.", "Mam kaszel.", "Gesundheit"],
["Ich kann nicht gut schlafen.", "Nie mogę dobrze spać.", "Gesundheit"],
["Ich habe Halsschmerzen.", "Boli mnie gardło.", "Gesundheit"],
["Wo ist das Krankenhaus?", "Gdzie jest szpital?", "Gesundheit"],
["Ich brauche ein Pflaster.", "Potrzebuję plastra.", "Gesundheit"],
["Bitte sprechen Sie langsam.", "Proszę mówić powoli.", "Gesundheit"],
["Ich verstehe nicht alles.", "Nie rozumiem wszystkiego.", "Gesundheit"]
].map(([de,target,category])=>({de,target,category}));
